export const FALLBACK_PRODUCTS = [
  {
    id: "dut-pekmezi",
    name: "Geleneksel İspir Dut Pekmezi",
    category: "pekmez",
    categoryDisplay: "Geleneksel Pekmezler",
    desc: "İspir'in 2000 rakımlı yaylalarındaki yabani mulberlerden toplanıp odun ateşinde ve bakır kazanlarda kaynatılan, katkısız saf dut pekmezi.",
    meta: "800g · Cam Kavanoz",
    price: 360,
    list_price: 400,
    sale_price: 360,
    cost: 180,
    stock: 142,
    stock_quantity: 142,
    criticalLimit: 10,
    isRawMaterial: false,
    image: "/uploads/1785870425901-o5xqxfpv2.webp",
    images: [
      "/uploads/1785870425901-o5xqxfpv2.webp",
      "/pekefe-dut-pekmezi-kavanoz-tr.jpg",
      "/ispir-pestil-kurutma-gercek.png"
    ],
    sku: "PRD-PK-001",
    status: "Stokta",
    variants: [
      { id: "v-dut-400", size: "400g Cam Kavanoz", price: 160, stock: 40, sku: "PRD-PK-001-400" },
      { id: "v-dut-800", size: "800g Cam Kavanoz", price: 280, stock: 142, sku: "PRD-PK-001-800" },
      { id: "v-dut-1kg", size: "1 Kg Vakum Ambalaj", price: 340, stock: 30, sku: "PRD-PK-001-1KG" }
    ]
  },
  {
    id: "karadut-pekmezi",
    name: "Yabani Karadut Pekmezi",
    category: "pekmez",
    categoryDisplay: "Geleneksel Pekmezler",
    desc: "Geleneksel vakumlu kaynatma tekniği ile yüksek HMF değerleri üretilmeden, vitamin ve mineralleri korunarak üretilen premium karadut özü.",
    meta: "450g · Şişe Şeklinde Cam",
    price: 450,
    list_price: 500,
    sale_price: 450,
    cost: 220,
    stock: 8,
    stock_quantity: 8,
    criticalLimit: 10,
    isRawMaterial: false,
    image: "/uploads/1785877091526-7ah5uox7t.webp",
    images: [
      "/uploads/1785877091526-7ah5uox7t.webp",
      "/premium-pekefe-kavanoz-tr.png",
      "/ispir-dut-hasadi.png"
    ],
    sku: "PRD-PK-042",
    status: "Kritik",
    variants: []
  },
  {
    id: "sade-pestil",
    name: "Sade Dut Pestili",
    category: "pestil",
    categoryDisplay: "Pestil & Köme",
    desc: "Dut şırası ve tam buğday ununun bakır kazanlarda pişirilip keten sergiler üzerinde İspir güneşi altında kurutulmasıyla üretilen incecik sade pestil.",
    meta: "500g · Kraft Kutu",
    price: 225,
    list_price: 250,
    sale_price: 225,
    cost: 110,
    stock: 64,
    stock_quantity: 64,
    criticalLimit: 15,
    isRawMaterial: false,
    image: "/uploads/1785879506228-y5wufiq7k.webp",
    images: [
      "/uploads/1785879506228-y5wufiq7k.webp",
      "/ispir-pestil-kurutma-gercek.png",
      "/ispir-vakum-sade-pestil-beyaz.png"
    ],
    sku: "PRD-PS-001",
    status: "Stokta",
    variants: []
  },
  {
    id: "cevizli-pestil",
    name: "Cevizli Dut Pestili",
    category: "pestil",
    categoryDisplay: "Pestil & Köme",
    desc: "İspir cevizleri ile zenginleştirilmiş, altın sarısı dut şırası yaprağına sarılı geleneksel cevizli pestil.",
    meta: "500g · Kraft Kutu",
    price: 285,
    list_price: 320,
    sale_price: 285,
    cost: 140,
    stock: 45,
    stock_quantity: 45,
    criticalLimit: 10,
    isRawMaterial: false,
    image: "/uploads/1785880000000-cevizli-pestil.webp",
    images: [
      "/uploads/1785880000000-cevizli-pestil.webp",
      "/ispir-pestil-kurutma-gercek.png"
    ],
    sku: "PRD-PS-002",
    status: "Stokta",
    variants: []
  },
  {
    id: "ispir-kome",
    name: "Cevizli İspir Kömesi (Cevizli Sucuk)",
    category: "kome",
    categoryDisplay: "Pestil & Köme",
    desc: "İplere dizilmiş iplik cevizlerin koyu dut şırasına defalarca batırılarak kurutulmasıyla yapılan köme.",
    meta: "500g · Vakum Ambalaj",
    price: 320,
    list_price: 360,
    sale_price: 320,
    cost: 160,
    stock: 52,
    stock_quantity: 52,
    criticalLimit: 10,
    isRawMaterial: false,
    image: "/uploads/1785881000000-ispir-kome.webp",
    images: [
      "/uploads/1785881000000-ispir-kome.webp",
      "/ispir-kome-gercek-hasat.jpg"
    ],
    sku: "PRD-KM-001",
    status: "Stokta",
    variants: []
  },
  {
    id: "gogermis-peynir",
    name: "Erzurum Göğermiş Peyniri",
    category: "peynir",
    categoryDisplay: "Yöresel Peynirler",
    desc: "İspir ve Çoruh vadisinin yüksek rakımlı yaylalarında otlayan inek sütlerinden yapılan doğal yeşil küflü göğermiş peynir.",
    meta: "1 Kg · Özel Vakum Ambalaj",
    price: 390,
    list_price: 440,
    sale_price: 390,
    cost: 200,
    stock: 28,
    stock_quantity: 28,
    criticalLimit: 5,
    isRawMaterial: false,
    image: "/uploads/1785882000000-gogermis-peynir.webp",
    images: [
      "/uploads/1785882000000-gogermis-peynir.webp"
    ],
    sku: "PRD-PY-001",
    status: "Stokta",
    variants: []
  },
  {
    id: "ispir-bali",
    name: "Saf İspir Çiçek Balı",
    category: "bal",
    categoryDisplay: "İspir Balı",
    desc: "Kaçkar dağlarının binbir çiçekli endemik florasından arıların topladığı %100 saf ve süzme çiçek balı.",
    meta: "850g · Cam Kavanoz",
    price: 650,
    list_price: 750,
    sale_price: 650,
    cost: 320,
    stock: 19,
    stock_quantity: 19,
    criticalLimit: 5,
    isRawMaterial: false,
    image: "/uploads/1785883000000-ispir-bali.webp",
    images: [
      "/uploads/1785883000000-ispir-bali.webp"
    ],
    sku: "PRD-BL-001",
    status: "Stokta",
    variants: []
  },
  {
    id: "koruk-ekipman",
    name: "Paslanmaz Galvaniz Arı Körüğü",
    category: "ekipman",
    categoryDisplay: "Arıcılık Ekipmanları",
    desc: "Isı koruma ızgaralı ve deri körük havalandırmalı profesyonel arıcılık körüğü.",
    meta: " Standart Boy",
    price: 290,
    list_price: 330,
    sale_price: 290,
    cost: 140,
    stock: 35,
    stock_quantity: 35,
    criticalLimit: 5,
    isRawMaterial: true,
    image: "/uploads/1785884000000-ari-koruk.webp",
    images: [
      "/uploads/1785884000000-ari-koruk.webp"
    ],
    sku: "EKP-AR-001",
    status: "Stokta",
    variants: []
  }
];
