export const FALLBACK_PRODUCTS = [
  {
    "id": "cmsp8zdcm0000q11zwciszj7g",
    "name": "Test Ürün",
    "sku": "PKF-559765",
    "category": "Pestil - Köme",
    "subCategory": null,
    "stock": 0,
    "criticalLimit": 5,
    "price": 1,
    "oldPrice": 2,
    "list_price": 2,
    "sale_price": 1,
    "discount_start_date": null,
    "discount_end_date": null,
    "stock_quantity": 0,
    "isCampaignActive": false,
    "cartDiscountRate": 0,
    "cost": 1,
    "image": "",
    "images": [],
    "desc": "",
    "seoTitle": "",
    "seoDesc": "",
    "seoKeywords": "",
    "videoUrl": "",
    "attributes": {
      "sizes": [
        "400g Cam Kavanoz",
        "800g Cam Kavanoz",
        "1 kg Vakum",
        "5 kg Teneke",
        "500 Gr",
        "1 Kg",
        "850g Cam Kavanoz",
        "450g Cam Kavanoz",
        "Paket"
      ],
      "colors": [
        "Sade",
        "Cevizli",
        "Fındıklı",
        "Antep Fıstıklı",
        "Kadayıflı",
        "Hindistan Cevizli"
      ],
      "barcode": "8699185320538",
      "unit": "Kg",
      "manufacturerCode": "PKF-DUT-4082",
      "stockType": "Ticari Mal",
      "warehouse": "Erzurum İspir Merkez Depo",
      "purchaseCurrency": "TRY",
      "purchaseVat": "20",
      "purchaseVatIncluded": false,
      "saleCurrency": "TRY",
      "saleVat": "20",
      "saleVatIncluded": true,
      "retailPrice": 1,
      "retailCurrency": "TRY",
      "retailVat": "20",
      "retailVatIncluded": true,
      "webPrice": 1,
      "webCurrency": "TRY",
      "webVat": "20",
      "webVatIncluded": true,
      "marketCurrency": "TRY",
      "marketVat": "20",
      "marketVatIncluded": true,
      "b2bActive": true,
      "b2bPreOrderable": false,
      "marketplaces": [
        {
          "id": "1",
          "name": "Trendyol API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "ty-api-90234892",
          "apiSecret": "••••••••",
          "logoColor": "bg-orange-500"
        },
        {
          "id": "2",
          "name": "Hepsiburada API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "hb-api-11029384",
          "apiSecret": "••••••••",
          "logoColor": "bg-red-600"
        },
        {
          "id": "3",
          "name": "Amazon Turkey API",
          "syncEnabled": false,
          "apiConnected": false,
          "logoColor": "bg-amber-500"
        }
      ],
      "shortDesc": "",
      "recipeDetails": "",
      "altitude": "2200 Metre",
      "harvestSeason": "Temmuz - Ağustos",
      "harvestStory": "",
      "ingredients": "",
      "ritual": "",
      "nutrients": {
        "energy": "293 kcal",
        "carb": "70.2 g",
        "protein": "0.8 g",
        "calcium": "400 mg",
        "iron": "10.2 mg"
      },
      "hmfLevel": "< 10 mg/kg (Analiz Raporlu)",
      "unitCoefficients": [],
      "branchPrices": {},
      "specsMaterial": "",
      "specsWeight": "",
      "specsDimensions": "",
      "specsBellows": "",
      "usageGuide": "",
      "warrantyInfo": "",
      "warrantyBadgeLabel": "",
      "warrantyYears": "",
      "warrantyBadgeDesc": "",
      "quickOverview1_title": "",
      "quickOverview1_desc": "",
      "quickOverview2_title": "",
      "quickOverview2_desc": "",
      "quickOverview3_title": "",
      "quickOverview3_desc": "",
      "quickOverview1": "",
      "quickOverview2": "",
      "quickOverview3": "",
      "longDescExtra": "",
      "badgeText1": "",
      "badgeText2": "",
      "warehousePrices": {},
      "brand": "Pekefe",
      "model": "Geleneksel Cam Kavanoz"
    },
    "isRawMaterial": false,
    "rating": 5,
    "reviews": 0,
    "isDeleted": false,
    "version": 1,
    "createdAt": "2026-08-11T22:44:17.110Z",
    "updatedAt": "2026-08-12T00:51:56.683Z",
    "companyId": null,
    "b2b_base_price": 1,
    "isDeal": false,
    "salesCount": 0,
    "variants": [],
    "locations": [
      {
        "id": "cmsp8zdcs0002q11zy9v71i92",
        "productId": "cmsp8zdcm0000q11zwciszj7g",
        "productVariantId": null,
        "warehouseId": "1",
        "stock": 0,
        "reserved": 0,
        "minStock": 0,
        "criticalLimit": 0,
        "rack": null,
        "warehouse": {
          "id": "1",
          "name": "İspir Üretim & Merkez Depo",
          "code": "WH-MRKZ",
          "type": "Merkez",
          "address": "Erzurum OSB, 3. Cadde",
          "isActive": true,
          "isLocked": false,
          "branchId": "default-branch",
          "companyId": null
        }
      },
      {
        "id": "cmsp8zdcx0004q11zlw40ipen",
        "productId": "cmsp8zdcm0000q11zwciszj7g",
        "productVariantId": null,
        "warehouseId": "2",
        "stock": 0,
        "reserved": 0,
        "minStock": 0,
        "criticalLimit": 0,
        "rack": null,
        "warehouse": {
          "id": "2",
          "name": "İstanbul Sevkiyat Şube Depo",
          "code": "WH-SUBE",
          "type": "Şube",
          "address": "İstanbul Anadolu Yakası",
          "isActive": true,
          "isLocked": false,
          "branchId": "sube-branch",
          "companyId": null
        }
      }
    ],
    "recipe": [],
    "retail_list_price": 2,
    "discount_amount": 1,
    "discount_percent": 50,
    "saving_amount": 1,
    "is_discounted": true,
    "discount_display_text": "%50 İndirim",
    "show_countdown": false,
    "server_time_utc": "2026-08-12T21:29:53.509Z",
    "b2b_price": null,
    "is_b2b_user": false,
    "volume_pricing_tiers": []
  },
  {
    "id": "cmsls1tah000oq1l0gublhh9q",
    "name": "PEKEFE Cevizli Dut Pestili",
    "sku": "PKF-803898",
    "category": "Pestil Köme Çeşitleri",
    "subCategory": null,
    "stock": 500,
    "criticalLimit": 10,
    "price": 500,
    "oldPrice": 550,
    "list_price": 0,
    "sale_price": 0,
    "discount_start_date": null,
    "discount_end_date": null,
    "stock_quantity": 0,
    "isCampaignActive": false,
    "cartDiscountRate": 0,
    "cost": 350,
    "image": "/uploads/1785884108715-kh0virvsq.webp",
    "images": [
      "/uploads/1785884108715-kh0virvsq.webp"
    ],
    "desc": "PEKEFE Geleneksel İspir Cevizli Dut Pestili İspir'in Geleneksel Lezzeti, Anadolu'nun En Değerli Ceviziyle Buluşuyor PEKEFE Geleneksel İspir Cevizli Dut Pestili , Erzurum'un İspir ilçesinin yüksek oksijenli mikroklima vadilerinde yetişen asırlık beyaz dut ağaçlarından elde edilen doğal dut şırasının, özenle seçilmiş kaliteli ceviz içiyle buluştuğu geleneksel bir lezzettir. Hasat döneminde el emeğiyle toplanan beyaz dutlar, yüzyıllardır sürdürülen İspir üretim kültürüne uygun yöntemlerle işlenir. Dutun doğal aroması ile cevizin zengin lezzeti, her lokmada Anadolu'nun köklü mutfak mirasını hissettirir. Geleneksel Üretim, Gerçek İspir Lezzeti Toplanan beyaz dutlardan elde edilen doğal dut şırası, bakır kazanlarda (herle) meşe odunu ateşinde kontrollü olarak pişirilir. Geleneksel tarif doğrultusunda az miktarda tam buğday unu ile kıvam kazandırılan şıra, saf keten bezler üzerine ince katmanlar hâlinde serilir. Doğal kuruma sürecinin ardından pestiller özenle hazırlanır ve içerisine seçkin ceviz içleri yerleştirilerek geleneksel yöntemlerle sarılır. Böylece hem yumuşak dokusu hem de cevizin kendine özgü aromasıyla zenginleşen eşsiz bir lezzet ortaya çıkar. İspir'in Güneşi ve Dağ Rüzgârlarıyla Doğal Kurutma PEKEFE Geleneksel İspir Cevizli Dut Pestili, İspir'in bol güneş ışığı ve nemsiz dağ rüzgârları sayesinde doğal olarak kurutulur. Bu geleneksel kurutma yöntemi, pestilin ince ve esnek yapısını korurken dutun doğal karamelize aromasının ve cevizin zengin lezzetinin uyum içinde gelişmesini sağlar. Her lokmada İspir'in doğasını ve geleneksel üretim ustalığını hissedersiniz. Katkısız ve Doğal İçerik PEKEFE'nin doğallık anlayışı üretimin her aşamasında korunur. Ürünümüzde; Glikoz şurubu kullanılmaz. Kimyasal koruyucu bulunmaz. Yapay renklendirici içermez. Yapay aroma içermez. Geleneksel tarif doğrultusunda hazırlanır. Doğal dut şırası ve özenle seçilmiş kaliteli ceviz, ürünümüzün temel bileşenlerini oluşturur. Dutun Zarafeti, Cevizin Zengin Aroması PEKEFE Geleneksel İspir Cevizli Dut Pestili; İncecik ve yumuşak dokusu, Dutun doğal karamelize aroması, Seçkin ceviz içinin yoğun lezzeti, Dengeli ve doyurucu yapısı ile geleneksel pestil kültürünü modern sofralara taşır. Tatlı ve cevizin doğal uyumu, her lokmada unutulmaz bir lezzet deneyimi sunar. Günün Her Anında Keyifle Tüketebilirsiniz PEKEFE Geleneksel İspir Cevizli Dut Pestili; Kahvaltılarda, Çay ve kahve yanında, Ara öğünlerde, Misafir ikramlarında, Günlük atıştırmalık olarak, Geleneksel lezzetleri sevenler için özel sunumlarda keyifle tüketilebilir. Doğal içeriği ve doyurucu yapısıyla günün her anına eşlik eden özel bir lezzettir. Neden PEKEFE? Çünkü PEKEFE yalnızca pestil üretmez. İspir'in asırlık dut ağaçlarını, geleneksel bakır kazanlarını, ustalarımızın emeğini ve Anadolu'nun en kıymetli lezzetlerinden biri olan cevizi aynı üründe buluşturur. Her ürünümüzde; ✓ İspir'in seçkin beyaz dutları, ✓ Özenle seçilmiş kaliteli ceviz içi, ✓ Geleneksel bakır kazan üretimi, ✓ Meşe odunu ateşinde pişirme yöntemi, ✓ Keten bezlerde doğal kurutma, ✓ Katkısız içerik anlayışı, ✓ Modern hijyen ve kalite standartları aynı titizlikle bir araya gelir. PEKEFE – Gelenekten Gelen Lezzetin En Zarif Hâli Asırlık beyaz dut ağaçlarından başlayan üretim yolculuğu, bakır kazanlarda ustalıkla hazırlanan doğal dut şırası, İspir'in güneşiyle kurutulan ince pestiller ve özenle seçilmiş ceviz içiyle tamamlanır. PEKEFE Geleneksel İspir Cevizli Dut Pestili , yalnızca geleneksel bir tatlı değil; İspir'in doğasını, ustalığını ve Anadolu'nun köklü lezzet mirasını sofralarınıza taşıyan seçkin bir lezzettir. PEKEFE İspir'in Doğallığı, Gelenekten Gelen Lezzet.",
    "seoTitle": null,
    "seoDesc": null,
    "seoKeywords": null,
    "videoUrl": null,
    "attributes": {
      "sizes": [
        "400g Cam Kavanoz",
        "800g Cam Kavanoz",
        "1 kg Vakum",
        "5 kg Teneke",
        "500 Gr",
        "1 Kg",
        "850g Cam Kavanoz",
        "450g Cam Kavanoz",
        "Paket"
      ],
      "colors": [
        "Sade",
        "Cevizli",
        "Fındıklı",
        "Antep Fıstıklı",
        "Kadayıflı",
        "Hindistan Cevizli"
      ],
      "barcode": "8686030765898",
      "unit": "Adet",
      "manufacturerCode": "PKF-CDP-01",
      "stockType": "Ticari Mal",
      "warehouse": "Merkez Depo",
      "origin": "İspir / Erzurum",
      "ingredients": "Doğal Dut Şırası, Erzurum Cevizi, Doğal Nişasta",
      "storageConditions": "Serin ve kuru yerde, doğrudan güneş ışığından uzakta muhafaza ediniz.",
      "pairing": "Pekefe Çamı Balı ve Erzurum Kıtlama Çayı eşliğinde sunulması tavsiye edilir.",
      "purchaseCurrency": "TRY",
      "purchaseVat": "1",
      "purchaseVatIncluded": false,
      "saleCurrency": "TRY",
      "saleVat": "1",
      "saleVatIncluded": true,
      "retailPrice": 500,
      "retailCurrency": "TRY",
      "retailVat": "1",
      "retailVatIncluded": true,
      "webPrice": 500,
      "webCurrency": "TRY",
      "webVat": "1",
      "webVatIncluded": true,
      "marketCurrency": "TRY",
      "marketVat": "1",
      "marketVatIncluded": true,
      "b2bActive": true,
      "b2bPreOrderable": false,
      "marketplaces": [
        {
          "id": "1",
          "name": "Trendyol API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "ty-api-90234892",
          "apiSecret": "••••••••",
          "logoColor": "bg-orange-500"
        },
        {
          "id": "2",
          "name": "Hepsiburada API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "hb-api-11029384",
          "apiSecret": "••••••••",
          "logoColor": "bg-red-600"
        },
        {
          "id": "3",
          "name": "Amazon Turkey API",
          "syncEnabled": false,
          "apiConnected": false,
          "logoColor": "bg-slate-500"
        }
      ],
      "shortDesc": "",
      "recipeDetails": "",
      "altitude": "2200 Metre",
      "harvestSeason": "Temmuz - Ağustos",
      "harvestStory": "",
      "ritual": "",
      "nutrients": {
        "energy": "293 kcal",
        "carb": "70.2 g",
        "protein": "0.8 g",
        "calcium": "400 mg",
        "iron": "10.2 mg"
      },
      "hmfLevel": "< 10 mg/kg (Analiz Raporlu)",
      "unitCoefficients": [],
      "branchPrices": {},
      "specsMaterial": "",
      "specsWeight": "",
      "specsDimensions": "",
      "specsBellows": "",
      "usageGuide": "",
      "warrantyInfo": "",
      "warrantyBadgeLabel": "",
      "warrantyYears": "",
      "warrantyBadgeDesc": "",
      "quickOverview1_title": "",
      "quickOverview1_desc": "",
      "quickOverview2_title": "",
      "quickOverview2_desc": "",
      "quickOverview3_title": "",
      "quickOverview3_desc": "",
      "quickOverview1": "",
      "quickOverview2": "",
      "quickOverview3": "",
      "longDescExtra": "",
      "badgeText1": "",
      "badgeText2": "",
      "warehousePrices": {},
      "brand": "",
      "model": ""
    },
    "isRawMaterial": false,
    "rating": 5,
    "reviews": 0,
    "isDeleted": false,
    "version": 1,
    "createdAt": "2026-08-09T12:26:59.081Z",
    "updatedAt": "2026-08-12T00:51:56.683Z",
    "companyId": null,
    "b2b_base_price": 0,
    "isDeal": false,
    "salesCount": 0,
    "variants": [],
    "locations": [
      {
        "id": "loc-merkez-cmsls1tah000oq1l0gublhh9q",
        "productId": "cmsls1tah000oq1l0gublhh9q",
        "productVariantId": null,
        "warehouseId": "1",
        "stock": 400,
        "reserved": 50,
        "minStock": 10,
        "criticalLimit": 15,
        "rack": "A-1",
        "warehouse": {
          "id": "1",
          "name": "İspir Üretim & Merkez Depo",
          "code": "WH-MRKZ",
          "type": "Merkez",
          "address": "Erzurum OSB, 3. Cadde",
          "isActive": true,
          "isLocked": false,
          "branchId": "default-branch",
          "companyId": null
        }
      }
    ],
    "recipe": [],
    "retail_list_price": 0,
    "discount_amount": 0,
    "discount_percent": 0,
    "saving_amount": 0,
    "is_discounted": false,
    "discount_display_text": "",
    "show_countdown": false,
    "server_time_utc": "2026-08-12T21:29:53.509Z",
    "b2b_price": null,
    "is_b2b_user": false,
    "volume_pricing_tiers": []
  },
  {
    "id": "cmsls1tab000nq1l01r2wdmsb",
    "name": "PEKEFE Dut Pestil Sarma Tatlısı 450 Gr",
    "sku": "PKF-962338",
    "category": "Pestil Köme Çeşitleri",
    "subCategory": null,
    "stock": 92,
    "criticalLimit": 10,
    "price": 350,
    "oldPrice": 400,
    "list_price": 0,
    "sale_price": 0,
    "discount_start_date": null,
    "discount_end_date": null,
    "stock_quantity": 0,
    "isCampaignActive": false,
    "cartDiscountRate": 0,
    "cost": 240,
    "image": "/uploads/1785881067849-c7goa2ycq.webp",
    "images": [
      "/uploads/1785881067849-c7goa2ycq.webp",
      "/uploads/1785881082446-gdhsawepb.webp",
      "/uploads/1785881093364-6rxpc3i3z.webp",
      "/uploads/1785881102424-dz7ufrtf5.webp",
      "/uploads/1785881110653-vs0nehrn3.webp",
      "/uploads/ispir-el-sarimi-pestil-cesitleri.webp"
    ],
    "desc": "Dut pestilinin içerisine bol miktarda dövülmüş fındık sarılarak hazırlanan lokum kıvamında gurme lezzet dilimleri.",
    "seoTitle": null,
    "seoDesc": null,
    "seoKeywords": null,
    "videoUrl": null,
    "attributes": {
      "shortDesc": "Dut pestilinin içerisine bol miktarda dövülmüş fındık sarılarak hazırlanan lokum kıvamında gurme lezzet dilimleri.",
      "details": "Geleneksel dut pestili yapraklarına bol dövülmüş ceviz içi sarılarak ince rulo dilimler elde edilir. Şekersiz doğal meyve tatlısıdır.",
      "harvestStory": "Geleneksel dut pestili yapraklarına bol dövülmüş fındık içi balla harmanlanıp sarılarak ince rulo dilimler elde edilir. Şekersiz doğal meyve tatlısıdır.",
      "ingredients": "İspir Beyaz Dut Pestili, Yerli Fındık İçi (%40)",
      "ritual": "Çay ve kahve saatlerinde sağlıklı tatlı alternatifi olarak tüketilir.",
      "altitude": "2000 Metre",
      "harvestSeason": "Temmuz - Ağustos",
      "hmfLevel": "< 10 mg/kg (Analiz Raporlu)",
      "nutrients": {
        "energy": "415 kcal",
        "carb": "74.0 g",
        "protein": "5.2 g",
        "calcium": "135 mg",
        "iron": "4.5 mg"
      },
      "specifications": [
        {
          "key": "Menşei",
          "value": "Erzurum / İspir"
        },
        {
          "key": "İçerik",
          "value": "İspir Cevizi Sarma"
        }
      ],
      "sizes": [
        "400g Cam Kavanoz",
        "800g Cam Kavanoz",
        "1 kg Vakum",
        "5 kg Teneke",
        "500 Gr",
        "1 Kg",
        "850g Cam Kavanoz",
        "450g Cam Kavanoz",
        "Paket"
      ],
      "colors": [
        "Sade",
        "Cevizli",
        "Fındıklı",
        "Antep Fıstıklı",
        "Kadayıflı",
        "Hindistan Cevizli"
      ],
      "barcode": "8699423577203",
      "unit": "Paket",
      "manufacturerCode": "PKF-PES-9722",
      "stockType": "Ticari Mal",
      "warehouse": "Merkez Depo",
      "purchaseCurrency": "TRY",
      "purchaseVat": "1",
      "purchaseVatIncluded": true,
      "saleCurrency": "TRY",
      "saleVat": "1",
      "saleVatIncluded": true,
      "retailPrice": 350,
      "retailCurrency": "TRY",
      "retailVat": "1",
      "retailVatIncluded": true,
      "webPrice": 350,
      "webCurrency": "TRY",
      "webVat": "1",
      "webVatIncluded": true,
      "marketCurrency": "TRY",
      "marketVat": "1",
      "marketVatIncluded": true,
      "b2bActive": true,
      "b2bPreOrderable": false,
      "marketplaces": [
        {
          "id": "1",
          "name": "Trendyol API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "ty-api-90234892",
          "apiSecret": "••••••••",
          "logoColor": "bg-orange-500"
        },
        {
          "id": "2",
          "name": "Hepsiburada API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "hb-api-11029384",
          "apiSecret": "••••••••",
          "logoColor": "bg-red-600"
        },
        {
          "id": "3",
          "name": "Amazon Turkey API",
          "syncEnabled": false,
          "apiConnected": false,
          "logoColor": "bg-slate-500"
        }
      ],
      "recipeDetails": "",
      "unitCoefficients": [],
      "branchPrices": {},
      "specsMaterial": "",
      "specsWeight": "",
      "specsDimensions": "",
      "specsBellows": "",
      "usageGuide": "",
      "warrantyInfo": "",
      "warrantyBadgeLabel": "",
      "warrantyYears": "",
      "warrantyBadgeDesc": "",
      "quickOverview1_title": "",
      "quickOverview1_desc": "",
      "quickOverview2_title": "",
      "quickOverview2_desc": "",
      "quickOverview3_title": "",
      "quickOverview3_desc": "",
      "quickOverview1": "",
      "quickOverview2": "",
      "quickOverview3": "",
      "longDescExtra": "",
      "badgeText1": "",
      "badgeText2": "",
      "warehousePrices": {},
      "brand": "",
      "model": ""
    },
    "isRawMaterial": false,
    "rating": 5,
    "reviews": 0,
    "isDeleted": false,
    "version": 1,
    "createdAt": "2026-08-09T12:26:59.075Z",
    "updatedAt": "2026-08-12T00:51:56.683Z",
    "companyId": null,
    "b2b_base_price": 0,
    "isDeal": false,
    "salesCount": 0,
    "variants": [],
    "locations": [
      {
        "id": "loc-merkez-cmsls1tab000nq1l01r2wdmsb",
        "productId": "cmsls1tab000nq1l01r2wdmsb",
        "productVariantId": null,
        "warehouseId": "1",
        "stock": 74,
        "reserved": 9,
        "minStock": 10,
        "criticalLimit": 15,
        "rack": "A-1",
        "warehouse": {
          "id": "1",
          "name": "İspir Üretim & Merkez Depo",
          "code": "WH-MRKZ",
          "type": "Merkez",
          "address": "Erzurum OSB, 3. Cadde",
          "isActive": true,
          "isLocked": false,
          "branchId": "default-branch",
          "companyId": null
        }
      }
    ],
    "recipe": [],
    "retail_list_price": 0,
    "discount_amount": 0,
    "discount_percent": 0,
    "saving_amount": 0,
    "is_discounted": false,
    "discount_display_text": "",
    "show_countdown": false,
    "server_time_utc": "2026-08-12T21:29:53.509Z",
    "b2b_price": null,
    "is_b2b_user": false,
    "volume_pricing_tiers": []
  },
  {
    "id": "cmsls1ta3000mq1l02gyeuorh",
    "name": "PEKEFE Dut Pestil Muska Tatlısı 450 Gr",
    "sku": "PKF-421384",
    "category": "Pestil Köme Çeşitleri",
    "subCategory": null,
    "stock": 100,
    "criticalLimit": 10,
    "price": 350,
    "oldPrice": 400,
    "list_price": 0,
    "sale_price": 0,
    "discount_start_date": null,
    "discount_end_date": null,
    "stock_quantity": 0,
    "isCampaignActive": false,
    "cartDiscountRate": 0,
    "cost": 240,
    "image": "/uploads/1785882201177-v93f9bbpg.webp",
    "images": [
      "/uploads/1785882201177-v93f9bbpg.webp",
      "/uploads/1785882215093-a1sp3fqs7.webp",
      "/uploads/1785882222824-8hgs8s5cu.webp",
      "/uploads/1785882247696-7r3y138q4.webp",
      "/uploads/1785882259010-8i3jvumz1.webp",
      "/uploads/ispir-muska-kome-saray-tatlilari.webp"
    ],
    "desc": "İncecik kesilen sade dut pestilinin içerisine yerli fındık, bal ve pekmez karışımı muska şeklinde sarılarak elde edilen saray lezzeti.",
    "seoTitle": null,
    "seoDesc": null,
    "seoKeywords": null,
    "videoUrl": null,
    "attributes": {
      "shortDesc": "İncecik kesilen sade dut pestilinin içerisine yerli Fındık, bal karışımı muska şeklinde sarılarak elde edilen saray lezzeti.",
      "details": "Keten sergilerde kurutulmuş ipeksi şerit pestillerin içerisine dövülmüş İspir cevizi ve saf bal dolgusu konarak muska biçiminde tek tek el emeğiyle katlanır.",
      "harvestStory": "Keten sergilerde kurutulmuş ipeksi şerit pestillerin içerisine dövülmüş yerli fındık ve saf bal dolgusu konarak muska biçiminde tek tek el emeğiyle katlanır.",
      "ingredients": "İspir Beyaz Dut Pestili, Fındık İçi, Saf Bal",
      "ritual": "Kahve yanında zarif bir saray ikramlığı olarak sunulabilir.",
      "altitude": "2000 Metre",
      "harvestSeason": "Temmuz - Ağustos",
      "hmfLevel": "< 10 mg/kg (Analiz Raporlu)",
      "nutrients": {
        "energy": "400 kcal",
        "carb": "76.0 g",
        "protein": "4.8 g",
        "calcium": "130 mg",
        "iron": "4.2 mg"
      },
      "specifications": [
        {
          "key": "Menşei",
          "value": "Erzurum / İspir"
        },
        {
          "key": "Dolgu",
          "value": "İspir Cevizi & Saf Bal"
        }
      ],
      "sizes": [
        "400g Cam Kavanoz",
        "800g Cam Kavanoz",
        "1 kg Vakum",
        "5 kg Teneke",
        "500 Gr",
        "1 Kg",
        "850g Cam Kavanoz",
        "450g Cam Kavanoz",
        "Paket"
      ],
      "colors": [
        "Sade",
        "Cevizli",
        "Fındıklı",
        "Antep Fıstıklı"
      ],
      "barcode": "8695108182976",
      "unit": "Paket",
      "manufacturerCode": "PKF-PES-9684",
      "stockType": "Ticari Mal",
      "warehouse": "Merkez Depo",
      "purchaseCurrency": "TRY",
      "purchaseVat": "1",
      "purchaseVatIncluded": false,
      "saleCurrency": "TRY",
      "saleVat": "1",
      "saleVatIncluded": true,
      "retailPrice": 350,
      "retailCurrency": "TRY",
      "retailVat": "1",
      "retailVatIncluded": true,
      "webPrice": 350,
      "webCurrency": "TRY",
      "webVat": "1",
      "webVatIncluded": true,
      "marketCurrency": "TRY",
      "marketVat": "1",
      "marketVatIncluded": true,
      "b2bActive": true,
      "b2bPreOrderable": false,
      "marketplaces": [
        {
          "id": "1",
          "name": "Trendyol API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "ty-api-90234892",
          "apiSecret": "••••••••",
          "logoColor": "bg-orange-500"
        },
        {
          "id": "2",
          "name": "Hepsiburada API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "hb-api-11029384",
          "apiSecret": "••••••••",
          "logoColor": "bg-red-600"
        },
        {
          "id": "3",
          "name": "Amazon Turkey API",
          "syncEnabled": false,
          "apiConnected": false,
          "logoColor": "bg-slate-500"
        }
      ],
      "recipeDetails": "",
      "unitCoefficients": [],
      "branchPrices": {},
      "specsMaterial": "",
      "specsWeight": "",
      "specsDimensions": "",
      "specsBellows": "",
      "usageGuide": "",
      "warrantyInfo": "",
      "warrantyBadgeLabel": "",
      "warrantyYears": "",
      "warrantyBadgeDesc": "",
      "quickOverview1_title": "",
      "quickOverview1_desc": "",
      "quickOverview2_title": "",
      "quickOverview2_desc": "",
      "quickOverview3_title": "",
      "quickOverview3_desc": "",
      "quickOverview1": "",
      "quickOverview2": "",
      "quickOverview3": "",
      "longDescExtra": "",
      "badgeText1": "",
      "badgeText2": "",
      "warehousePrices": {},
      "brand": "",
      "model": ""
    },
    "isRawMaterial": false,
    "rating": 5,
    "reviews": 0,
    "isDeleted": false,
    "version": 1,
    "createdAt": "2026-08-09T12:26:59.068Z",
    "updatedAt": "2026-08-12T00:51:56.683Z",
    "companyId": null,
    "b2b_base_price": 0,
    "isDeal": false,
    "salesCount": 0,
    "variants": [],
    "locations": [
      {
        "id": "loc-merkez-cmsls1ta3000mq1l02gyeuorh",
        "productId": "cmsls1ta3000mq1l02gyeuorh",
        "productVariantId": null,
        "warehouseId": "1",
        "stock": 80,
        "reserved": 10,
        "minStock": 10,
        "criticalLimit": 15,
        "rack": "A-1",
        "warehouse": {
          "id": "1",
          "name": "İspir Üretim & Merkez Depo",
          "code": "WH-MRKZ",
          "type": "Merkez",
          "address": "Erzurum OSB, 3. Cadde",
          "isActive": true,
          "isLocked": false,
          "branchId": "default-branch",
          "companyId": null
        }
      }
    ],
    "recipe": [],
    "retail_list_price": 0,
    "discount_amount": 0,
    "discount_percent": 0,
    "saving_amount": 0,
    "is_discounted": false,
    "discount_display_text": "",
    "show_countdown": false,
    "server_time_utc": "2026-08-12T21:29:53.509Z",
    "b2b_price": null,
    "is_b2b_user": false,
    "volume_pricing_tiers": []
  },
  {
    "id": "cmsls1t9x000lq1l0tsi0mu9t",
    "name": "PEKEFE İspir Tek Çekim Dut Kömesi (Cevizli)",
    "sku": "PKF-156882",
    "category": "Pestil Köme Çeşitleri",
    "subCategory": null,
    "stock": 92,
    "criticalLimit": 10,
    "price": 650,
    "oldPrice": 700,
    "list_price": 0,
    "sale_price": 0,
    "discount_start_date": null,
    "discount_end_date": null,
    "stock_quantity": 0,
    "isCampaignActive": false,
    "cartDiscountRate": 0,
    "cost": 440,
    "image": "/ispir-kome-beyaz.png",
    "images": [
      "/ispir-kome-beyaz.png"
    ],
    "desc": "İpe dizili cevizlere tek kat daldırma yapılarak ceviz yoğunluğu en üst seviyede tutulmuş, az herle kaplı butik seri köme.",
    "seoTitle": null,
    "seoDesc": null,
    "seoKeywords": null,
    "videoUrl": null,
    "attributes": {
      "shortDesc": "İpe dizili cevizlere tek kat daldırma yapılarak ceviz yoğunluğu en üst seviyede tutulmuş, az herle kaplı butik seri köme.",
      "details": "Ceviz lezzetini öne çıkarmak için ipe dizilen kelebek cevizler dut herlesine tek daldırma ile kaplanır. Ceviz oranı maksimumda tutulan hafif ve gevreğimsi gurme serimizdir.",
      "harvestStory": "Ceviz lezzetini öne çıkarmak için ipe dizilen kelebek cevizler dut herlesine tek daldırma ile kaplanır. Ceviz oranı maksimumda tutulan hafif ve gevreğimsi gurme serimizdir.",
      "ingredients": "Yerli İspir Cevizi (%55), İspir Beyaz Dut Şırası, Tam Buğday Unu",
      "ritual": "Tek lokmalık dilimler halinde servis edilir.",
      "altitude": "2000 Metre",
      "harvestSeason": "Ağustos - Eylül",
      "hmfLevel": "< 10 mg/kg (Analiz Raporlu)",
      "nutrients": {
        "energy": "460 kcal",
        "carb": "58.0 g",
        "protein": "8.2 g",
        "calcium": "160 mg",
        "iron": "5.8 mg"
      },
      "specifications": [
        {
          "key": "Menşei",
          "value": "Erzurum / İspir"
        },
        {
          "key": "Ceviz Oranı",
          "value": "%55 (Ekstra Yoğun Ceviz)"
        }
      ],
      "sizes": [
        "400g Cam Kavanoz",
        "800g Cam Kavanoz",
        "1 kg Vakum",
        "5 kg Teneke",
        "500 Gr",
        "1 Kg",
        "850g Cam Kavanoz",
        "450g Cam Kavanoz",
        "Paket"
      ],
      "colors": [
        "Sade",
        "Cevizli",
        "Fındıklı",
        "Antep Fıstıklı",
        "Kadayıflı",
        "Hindistan Cevizli"
      ],
      "barcode": "8693235740067",
      "unit": "Kg",
      "manufacturerCode": "PKF-PES-2443",
      "stockType": "Ticari Mal",
      "warehouse": "Merkez Depo",
      "purchaseCurrency": "TRY",
      "purchaseVat": "1",
      "purchaseVatIncluded": true,
      "saleCurrency": "TRY",
      "saleVat": "1",
      "saleVatIncluded": true,
      "retailPrice": 650,
      "retailCurrency": "TRY",
      "retailVat": "1",
      "retailVatIncluded": true,
      "webPrice": 650,
      "webCurrency": "TRY",
      "webVat": "1",
      "webVatIncluded": true,
      "marketCurrency": "TRY",
      "marketVat": "1",
      "marketVatIncluded": true,
      "b2bActive": true,
      "b2bPreOrderable": false,
      "marketplaces": [
        {
          "id": "1",
          "name": "Trendyol API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "ty-api-90234892",
          "apiSecret": "••••••••",
          "logoColor": "bg-orange-500"
        },
        {
          "id": "2",
          "name": "Hepsiburada API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "hb-api-11029384",
          "apiSecret": "••••••••",
          "logoColor": "bg-red-600"
        },
        {
          "id": "3",
          "name": "Amazon Turkey API",
          "syncEnabled": false,
          "apiConnected": false,
          "logoColor": "bg-slate-500"
        }
      ],
      "recipeDetails": "",
      "unitCoefficients": [],
      "branchPrices": {},
      "specsMaterial": "",
      "specsWeight": "",
      "specsDimensions": "",
      "specsBellows": "",
      "usageGuide": "",
      "warrantyInfo": "",
      "warrantyBadgeLabel": "",
      "warrantyYears": "",
      "warrantyBadgeDesc": "",
      "quickOverview1_title": "",
      "quickOverview1_desc": "",
      "quickOverview2_title": "",
      "quickOverview2_desc": "",
      "quickOverview3_title": "",
      "quickOverview3_desc": "",
      "quickOverview1": "",
      "quickOverview2": "",
      "quickOverview3": "",
      "longDescExtra": "",
      "badgeText1": "",
      "badgeText2": "",
      "warehousePrices": {},
      "brand": "",
      "model": ""
    },
    "isRawMaterial": false,
    "rating": 5,
    "reviews": 0,
    "isDeleted": false,
    "version": 1,
    "createdAt": "2026-08-09T12:26:59.061Z",
    "updatedAt": "2026-08-12T00:51:56.683Z",
    "companyId": null,
    "b2b_base_price": 0,
    "isDeal": false,
    "salesCount": 0,
    "variants": [],
    "locations": [
      {
        "id": "loc-merkez-cmsls1t9x000lq1l0tsi0mu9t",
        "productId": "cmsls1t9x000lq1l0tsi0mu9t",
        "productVariantId": null,
        "warehouseId": "1",
        "stock": 74,
        "reserved": 9,
        "minStock": 10,
        "criticalLimit": 15,
        "rack": "A-1",
        "warehouse": {
          "id": "1",
          "name": "İspir Üretim & Merkez Depo",
          "code": "WH-MRKZ",
          "type": "Merkez",
          "address": "Erzurum OSB, 3. Cadde",
          "isActive": true,
          "isLocked": false,
          "branchId": "default-branch",
          "companyId": null
        }
      }
    ],
    "recipe": [],
    "retail_list_price": 0,
    "discount_amount": 0,
    "discount_percent": 0,
    "saving_amount": 0,
    "is_discounted": false,
    "discount_display_text": "",
    "show_countdown": false,
    "server_time_utc": "2026-08-12T21:29:53.509Z",
    "b2b_price": null,
    "is_b2b_user": false,
    "volume_pricing_tiers": []
  },
  {
    "id": "cmsls1t9a000kq1l0gj4ighi8",
    "name": "PEKEFE İspir Dut Kömesi (Cevizli)",
    "sku": "PKF-636433",
    "category": "Pestil Köme Çeşitleri",
    "subCategory": null,
    "stock": 99,
    "criticalLimit": 10,
    "price": 600,
    "oldPrice": 650,
    "list_price": 0,
    "sale_price": 0,
    "discount_start_date": null,
    "discount_end_date": null,
    "stock_quantity": 0,
    "isCampaignActive": false,
    "cartDiscountRate": 0,
    "cost": 420,
    "image": "/ispir-kome-gercek-hasat.jpg",
    "images": [
      "/ispir-kome-gercek-hasat.jpg",
      "/uploads/ispir-muska-kome-saray-tatlilari.webp"
    ],
    "desc": "İpe dizilen taze İspir cevizlerinin, bakır kazanlarda kaynayan dut herlesine defalarca batırılarak güneşte kurutulmasıyla elde edilen coğrafi işaretli lezzet.",
    "seoTitle": null,
    "seoDesc": null,
    "seoKeywords": null,
    "videoUrl": null,
    "attributes": {
      "shortDesc": "İpe dizilen taze İspir cevizlerinin, bakır kazanlarda kaynayan dut herlesine defalarca batırılarak güneşte kurutulmasıyla elde edilen coğrafi işaretli lezzet.",
      "details": "Pamuk iplerine dizilen kelebek İspir cevizleri, meşe odunu ateşinde kaynayan yoğun dut herlesine (şıra ve un karışımı) birkaç kat halinde daldırılır.\n\nİspir dağ rüzgarında askılarda kurutulan kömelerimiz, dışı yumuşacık ve esnek, içi bol cevizli asırlık bir gelenek sunar.",
      "harvestStory": "Pamuk iplerine dizilen kelebek İspir cevizleri, meşe odunu ateşinde kaynayan yoğun dut herlesine (şıra ve un karışımı) birkaç kat halinde daldırılır.\n\nİspir dağ rüzgarında askılarda kurutulan kömelerimiz, dışı yumuşacık ve esnek, içi bol cevizli asırlık bir gelenek sunar.",
      "ingredients": "İspir Beyaz Dut Şırası, Tam Buğday Unu, Yerli İspir Cevizi (%40)",
      "ritual": "Oda sıcaklığında dilimlenerek ikram edilir. Çay ve Türk kahvesinin yanında besleyici geleneksel ikramlıktır.",
      "altitude": "2000 Metre",
      "harvestSeason": "Ağustos - Eylül",
      "hmfLevel": "< 10 mg/kg (Analiz Raporlu)",
      "nutrients": {
        "energy": "430 kcal",
        "carb": "68.0 g",
        "protein": "6.5 g",
        "calcium": "150 mg",
        "iron": "5.2 mg"
      },
      "specifications": [
        {
          "key": "Menşei",
          "value": "Erzurum / İspir"
        },
        {
          "key": "Ceviz Oranı",
          "value": "%40 (Yerli Kelebek Ceviz)"
        },
        {
          "key": "Ambalaj",
          "value": "Pamuk Torba / Vakum Kutu"
        }
      ],
      "sizes": [
        "400g Cam Kavanoz",
        "800g Cam Kavanoz",
        "1 kg Vakum",
        "5 kg Teneke",
        "500 Gr",
        "1 Kg",
        "850g Cam Kavanoz",
        "450g Cam Kavanoz",
        "Paket"
      ],
      "colors": [
        "Sade",
        "Cevizli",
        "Fındıklı",
        "Antep Fıstıklı",
        "Kadayıflı",
        "Hindistan Cevizli"
      ],
      "barcode": "8691463708460",
      "unit": "Kg",
      "manufacturerCode": "PKF-PES-2543",
      "stockType": "Ticari Mal",
      "warehouse": "Merkez Depo",
      "purchaseCurrency": "TRY",
      "purchaseVat": "1",
      "purchaseVatIncluded": true,
      "saleCurrency": "TRY",
      "saleVat": "1",
      "saleVatIncluded": true,
      "retailPrice": 600,
      "retailCurrency": "TRY",
      "retailVat": "1",
      "retailVatIncluded": true,
      "webPrice": 600,
      "webCurrency": "TRY",
      "webVat": "1",
      "webVatIncluded": true,
      "marketCurrency": "TRY",
      "marketVat": "1",
      "marketVatIncluded": true,
      "b2bActive": true,
      "b2bPreOrderable": false,
      "marketplaces": [
        {
          "id": "1",
          "name": "Trendyol API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "ty-api-90234892",
          "apiSecret": "••••••••",
          "logoColor": "bg-orange-500"
        },
        {
          "id": "2",
          "name": "Hepsiburada API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "hb-api-11029384",
          "apiSecret": "••••••••",
          "logoColor": "bg-red-600"
        },
        {
          "id": "3",
          "name": "Amazon Turkey API",
          "syncEnabled": false,
          "apiConnected": false,
          "logoColor": "bg-slate-500"
        }
      ],
      "recipeDetails": "",
      "unitCoefficients": [],
      "branchPrices": {},
      "specsMaterial": "",
      "specsWeight": "",
      "specsDimensions": "",
      "specsBellows": "",
      "usageGuide": "",
      "warrantyInfo": "",
      "warrantyBadgeLabel": "",
      "warrantyYears": "",
      "warrantyBadgeDesc": "",
      "quickOverview1_title": "",
      "quickOverview1_desc": "",
      "quickOverview2_title": "",
      "quickOverview2_desc": "",
      "quickOverview3_title": "",
      "quickOverview3_desc": "",
      "quickOverview1": "",
      "quickOverview2": "",
      "quickOverview3": "",
      "longDescExtra": "",
      "badgeText1": "",
      "badgeText2": "",
      "warehousePrices": {},
      "brand": "",
      "model": ""
    },
    "isRawMaterial": false,
    "rating": 5,
    "reviews": 0,
    "isDeleted": false,
    "version": 1,
    "createdAt": "2026-08-09T12:26:59.038Z",
    "updatedAt": "2026-08-12T00:51:56.683Z",
    "companyId": null,
    "b2b_base_price": 0,
    "isDeal": false,
    "salesCount": 0,
    "variants": [],
    "locations": [
      {
        "id": "loc-merkez-cmsls1t9a000kq1l0gj4ighi8",
        "productId": "cmsls1t9a000kq1l0gj4ighi8",
        "productVariantId": null,
        "warehouseId": "1",
        "stock": 79,
        "reserved": 10,
        "minStock": 10,
        "criticalLimit": 15,
        "rack": "A-1",
        "warehouse": {
          "id": "1",
          "name": "İspir Üretim & Merkez Depo",
          "code": "WH-MRKZ",
          "type": "Merkez",
          "address": "Erzurum OSB, 3. Cadde",
          "isActive": true,
          "isLocked": false,
          "branchId": "default-branch",
          "companyId": null
        }
      }
    ],
    "recipe": [],
    "retail_list_price": 0,
    "discount_amount": 0,
    "discount_percent": 0,
    "saving_amount": 0,
    "is_discounted": false,
    "discount_display_text": "",
    "show_countdown": false,
    "server_time_utc": "2026-08-12T21:29:53.509Z",
    "b2b_price": null,
    "is_b2b_user": false,
    "volume_pricing_tiers": []
  },
  {
    "id": "cmsls1t8n000iq1l0vo0mcdrx",
    "name": "PEKEFE Sade Dut Pestili",
    "sku": "PKF-368593",
    "category": "Pestil Köme Çeşitleri",
    "subCategory": null,
    "stock": 1000,
    "criticalLimit": 10,
    "price": 450,
    "oldPrice": 500,
    "list_price": 0,
    "sale_price": 0,
    "discount_start_date": null,
    "discount_end_date": null,
    "stock_quantity": 0,
    "isCampaignActive": false,
    "cartDiscountRate": 0,
    "cost": 320,
    "image": "/uploads/1785879506228-y5wufiq7k.webp",
    "images": [
      "/uploads/1785879506228-y5wufiq7k.webp",
      "/uploads/ispir-keten-bezde-pestil-serimi.webp",
      "/ispir-pestil-kurutma-gercek.png"
    ],
    "desc": "PEKEFE Geleneksel İspir Sade Dut Pestili İspir'in Güneşiyle Olgunlaşan Geleneksel Lezzet PEKEFE Geleneksel İspir Sade Dut Pestili , Erzurum'un İspir ilçesinin yüksek oksijenli mikroklima vadilerinde yetişen asırlık beyaz dut ağaçlarının özenle seçilen meyvelerinden üretilir. Hasat döneminde olgunlaşan dutlar, geleneksel yöntemlerle el emeğiyle toplanarak üretime alınır. Her pestil yaprağı, İspir'in bereketli topraklarını, temiz havasını ve yüzyıllardır yaşatılan üretim kültürünü sofralarınıza taşıyan doğal bir lezzet mirasıdır. Geleneksel Üretimle Hazırlanan Gerçek İspir Pestili Toplanan beyaz dutlardan elde edilen doğal dut şırası, hiçbir yapay katkıya ihtiyaç duyulmadan geleneksel yöntemlerle hazırlanır. Şıra, bakır kazanlarda (herle) meşe odunu ateşinde kontrollü şekilde pişirilir. Kıvamını almasının ardından, geleneksel tarifin gerektirdiği ölçüde tam buğday unu ile bağlanır ve ustalıkla saf keten bezler üzerine ince katmanlar hâlinde serilir. Bu yöntem, İspir'de nesiller boyunca aktarılan pestil üretim geleneğinin en önemli aşamalarından biridir. Güneş ve Dağ Rüzgârının Doğal Dokunuşu PEKEFE Geleneksel İspir Sade Dut Pestili'nin en önemli özelliklerinden biri, doğal kurutma sürecidir. Keten bezler üzerine serilen pestiller, İspir'in bol güneş ışığı ve nemsiz dağ rüzgârları eşliğinde doğal olarak kurutulur. Uygun kıvama ulaştığında özenle bezlerinden ayrılır ve geleneksel dokusunu koruyacak şekilde hazırlanır. Bu doğal süreç, pestilin ince yapısını, yumuşak dokusunu ve kendine özgü aromasını oluşturan en önemli unsurlardan biridir. Katkısız ve Doğal İçerik PEKEFE'nin üretim anlayışının temelinde doğallık yer alır. Ürünümüzde; Glikoz şurubu kullanılmaz. Kimyasal koruyucu bulunmaz. Yapay renklendirici içermez. Yapay aroma içermez. Geleneksel tarif doğrultusunda hazırlanır. Saf dutun doğal lezzeti ve geleneksel üretim ustalığı, ürünümüzün en değerli özelliğidir. İncecik Dokusu, Yoğun Dut Aroması PEKEFE Geleneksel İspir Sade Dut Pestili; İncecik ve esnek yapısı, İpeksi dokusu, Dutun doğal karamelize aroması, Dengeli ve hafif tatlı lezzeti ile geleneksel pestil severlerin vazgeçilmez tercihidir. Her lokmada beyaz dutun doğal aroması ve İspir'in eşsiz üretim kültürü hissedilir. Günün Her Saatinde Doğal Bir Atıştırmalık PEKEFE Geleneksel İspir Sade Dut Pestili; Kahvaltılarda, Çay ve kahve yanında, Ara öğünlerde, Spor öncesi veya sonrası pratik bir atıştırmalık olarak, Çocukların beslenme çantasında, Misafir ikramlarında keyifle tüketilebilir. Dilerseniz ceviz, fındık veya badem ile birlikte tüketerek geleneksel lezzeti farklı tatlarla zenginleştirebilirsiniz. Neden PEKEFE? Çünkü PEKEFE yalnızca pestil üretmez. İspir'in doğasını, asırlık dut ağaçlarını, geleneksel bakır kazanlarını ve ustalarımızın emeğini geleceğe taşıyan bir kültürü yaşatır. Her ürünümüzde; ✓ İspir'in seçkin beyaz dutları, ✓ Geleneksel bakır kazan üretimi, ✓ Meşe odunu ateşinde pişirme yöntemi, ✓ Keten bezlerde doğal kurutma, ✓ Katkısız içerik anlayışı, ✓ Modern hijyen ve kalite standartları aynı özenle buluşur. PEKEFE – İspir'in Doğallığını Her Lokmada Hissedin Asırlık beyaz dut ağaçlarından başlayan, geleneksel bakır kazanlarda devam eden ve İspir'in güneşiyle tamamlanan bu yolculuk; her lokmada doğallığı, emeği ve ustalığı hissettirir. PEKEFE Geleneksel İspir Sade Dut Pestili , yalnızca geleneksel bir atıştırmalık değil; Anadolu'nun köklü üretim kültürünü ve İspir'in eşsiz doğasını sofralarınıza taşıyan özel bir lezzettir. PEKEFE İspir'in Doğallığı, Gelenekten Gelen Lezzet.",
    "seoTitle": null,
    "seoDesc": null,
    "seoKeywords": null,
    "videoUrl": null,
    "attributes": {
      "shortDesc": "İspir’in yüksek rakımlı vadilerinde yetişen beyaz dut şırası ve tam buğday ununun bakır kazanlarda pişirilip keten sergilerde güneşte kurutulmasıyla hazırlanan ipeksi sade pestil.",
      "details": "PEKEFE Sade Dut Pestili, Erzurum İspir’in yüksek oksijenli mikroklimal vadilerinde yetişen asırlık dut ağaçlarından el emeğiyle toplanan saf beyaz dutlardan üretilir.\n\nHiçbir kimyasal koruyucu veya glikoz şurubu içermeyen doğal dut şırası, geleneksel bakır kazanlarda meşe odunu ateşinde pişirilir. Az miktarda tam buğday unu ile bağlanan ipeksi şıra, saf keten bezler üzerine dökülür.\n\nİspir'in nemsiz dağ rüzgarları ve bol güneş ışığı altında doğal olarak kurutulan pestiller, kıvamını bulunca sergilerden özenle sıyrılır. İncecik dokusu ve karamelize aromasıyla rafine bir lezzettir.",
      "harvestStory": "PEKEFE Sade Dut Pestili, Erzurum İspir’in yüksek oksijenli mikroklimal vadilerinde yetişen asırlık dut ağaçlarından el emeğiyle toplanan saf beyaz dutlardan üretilir.\n\nHiçbir kimyasal koruyucu veya glikoz şurubu içermeyen doğal dut şırası, geleneksel bakır kazanlarda meşe odunu ateşinde pişirilir. Az miktarda tam buğday unu ile bağlanan ipeksi şıra, saf keten bezler üzerine dökülür.\n\nİspir'in nemsiz dağ rüzgarları ve bol güneş ışığı altında doğal olarak kurutulan pestiller, kıvamını bulunca sergilerden özenle sıyrılır. İncecik dokusu ve karamelize aromasıyla rafine bir lezzettir.",
      "ingredients": "%100 Saf İspir Beyaz Dut Şırası, Tam Buğday Unu",
      "ritual": "Oda sıcaklığında (18°C - 22°C), yanında taze demlenmiş Türk kahvesi veya bergamat aromalı çay ile servis edilmesi önerilir. İsteğe göre içerisine keçi peyniri sarılabilir.",
      "altitude": "2000 Metre",
      "harvestSeason": "Temmuz - Ağustos",
      "hmfLevel": "< 10 mg/kg (Analiz Raporlu)",
      "nutrients": {
        "energy": "380 kcal",
        "carb": "82.0 g",
        "protein": "3.5 g",
        "calcium": "120 mg",
        "iron": "4.0 mg"
      },
      "specifications": [
        {
          "key": "Menşei",
          "value": "Erzurum / İspir"
        },
        {
          "key": "Kurutma Yöntemi",
          "value": "Keten Bezlerde Güneşte Doğal Kurutma"
        },
        {
          "key": "Kalınlık",
          "value": "< 1.5 mm (İpeksi Dokulu)"
        },
        {
          "key": "Şeker / Glikoz",
          "value": "0.0% (Sadece Doğal Meyve Şekeri)"
        }
      ],
      "sizes": [
        "400g Cam Kavanoz",
        "800g Cam Kavanoz",
        "1 kg Vakum",
        "5 kg Teneke",
        "850g Cam Kavanoz",
        "450g Cam Kavanoz",
        "1 Kg",
        "500 Gr"
      ],
      "colors": [
        "Sade",
        "Cevizli",
        "Fındıklı",
        "Antep Fıstıklı"
      ],
      "barcode": "8699566620483",
      "unit": "Kg",
      "manufacturerCode": "PKF-PES-4309",
      "stockType": "Ticari Mal",
      "warehouse": "Merkez Depo",
      "purchaseCurrency": "TRY",
      "purchaseVat": "1",
      "purchaseVatIncluded": false,
      "saleCurrency": "TRY",
      "saleVat": "1",
      "saleVatIncluded": true,
      "retailPrice": 450,
      "retailCurrency": "TRY",
      "retailVat": "1",
      "retailVatIncluded": true,
      "webPrice": 450,
      "webCurrency": "TRY",
      "webVat": "1",
      "webVatIncluded": true,
      "marketCurrency": "TRY",
      "marketVat": "1",
      "marketVatIncluded": true,
      "b2bActive": true,
      "b2bPreOrderable": false,
      "marketplaces": [
        {
          "id": "1",
          "name": "Trendyol API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "ty-api-90234892",
          "apiSecret": "••••••••",
          "logoColor": "bg-orange-500"
        },
        {
          "id": "2",
          "name": "Hepsiburada API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "hb-api-11029384",
          "apiSecret": "••••••••",
          "logoColor": "bg-red-600"
        },
        {
          "id": "3",
          "name": "Amazon Turkey API",
          "syncEnabled": false,
          "apiConnected": false,
          "logoColor": "bg-slate-500"
        }
      ],
      "recipeDetails": "",
      "unitCoefficients": [],
      "branchPrices": {},
      "specsMaterial": "",
      "specsWeight": "",
      "specsDimensions": "",
      "specsBellows": "",
      "usageGuide": "",
      "warrantyInfo": "",
      "warrantyBadgeLabel": "",
      "warrantyYears": "",
      "warrantyBadgeDesc": "",
      "quickOverview1_title": "",
      "quickOverview1_desc": "",
      "quickOverview2_title": "",
      "quickOverview2_desc": "",
      "quickOverview3_title": "",
      "quickOverview3_desc": "",
      "quickOverview1": "",
      "quickOverview2": "",
      "quickOverview3": "",
      "longDescExtra": "",
      "badgeText1": "",
      "badgeText2": "",
      "warehousePrices": {},
      "brand": "",
      "model": ""
    },
    "isRawMaterial": false,
    "rating": 5,
    "reviews": 0,
    "isDeleted": false,
    "version": 1,
    "createdAt": "2026-08-09T12:26:59.015Z",
    "updatedAt": "2026-08-12T00:51:56.683Z",
    "companyId": null,
    "b2b_base_price": 0,
    "isDeal": false,
    "salesCount": 0,
    "variants": [],
    "locations": [
      {
        "id": "loc-merkez-cmsls1t8n000iq1l0vo0mcdrx",
        "productId": "cmsls1t8n000iq1l0vo0mcdrx",
        "productVariantId": null,
        "warehouseId": "1",
        "stock": 800,
        "reserved": 100,
        "minStock": 10,
        "criticalLimit": 15,
        "rack": "A-1",
        "warehouse": {
          "id": "1",
          "name": "İspir Üretim & Merkez Depo",
          "code": "WH-MRKZ",
          "type": "Merkez",
          "address": "Erzurum OSB, 3. Cadde",
          "isActive": true,
          "isLocked": false,
          "branchId": "default-branch",
          "companyId": null
        }
      }
    ],
    "recipe": [],
    "retail_list_price": 0,
    "discount_amount": 0,
    "discount_percent": 0,
    "saving_amount": 0,
    "is_discounted": false,
    "discount_display_text": "",
    "show_countdown": false,
    "server_time_utc": "2026-08-12T21:29:53.509Z",
    "b2b_price": null,
    "is_b2b_user": false,
    "volume_pricing_tiers": []
  },
  {
    "id": "cmsls1t84000hq1l0fcp06wcw",
    "name": "PEKEFE İspir Karadut Pekmezi",
    "sku": "PKF-499290",
    "category": "Pekmez ÇeşitLeri",
    "subCategory": null,
    "stock": 1000,
    "criticalLimit": 10,
    "price": 1000,
    "oldPrice": 1050,
    "list_price": 0,
    "sale_price": 0,
    "discount_start_date": null,
    "discount_end_date": null,
    "stock_quantity": 0,
    "isCampaignActive": false,
    "cartDiscountRate": 0,
    "cost": 560,
    "image": "/uploads/1785877091526-7ah5uox7t.webp",
    "images": [
      "/uploads/1785877091526-7ah5uox7t.webp",
      "/uploads/1785877098808-oq559xwyn.webp",
      "/uploads/1785877117745-hoyp6xxz0.webp",
      "/uploads/1785877124124-g4c9n8ek9.webp",
      "/uploads/1785877186234-29wv3y09f.webp",
      "/uploads/ispir-karadut-kaynatma-bakir-kazan.webp",
      "/uploads/1785877153252-4pczqre3d.mp4",
      "/uploads/1785877157277-6g7dpx2vc.webp"
    ],
    "desc": "PEKEFE Geleneksel İspir Karadut Pekmezi İspir'in Bereketli Karadutlarından Gelen Yoğun Lezzet PEKEFE Geleneksel İspir Karadut Pekmezi , Erzurum'un İspir ilçesinin temiz havası, yüksek rakımı ve verimli vadilerinde yetişen seçkin karadut meyvelerinden üretilir. Hasat döneminde olgunlaşan karadutlar, günün serinliği korunurken şafak vakti büyük bir özenle toplanır. Meyveler tazeliğini kaybetmeden işlenerek doğal karakterini koruyan saf karadut şırasına dönüştürülür. Her kavanoz, İspir'in bereketli doğasını, üreticilerimizin emeğini ve PEKEFE'nin kalite anlayışını sofralarınıza taşır. Besin Değerlerini Korumaya Odaklanan Üretim Toplanan karadutlar hassas şekilde preslenerek elde edilen şıra, düşük sıcaklıkta çalışan vakumlu kazanlarda kontrollü olarak yoğunlaştırılır. Bu özel üretim yöntemi sayesinde yüksek sıcaklığın oluşturabileceği kalite kayıpları en aza indirilirken, karadutun doğal aroması, rengi ve karakteristik yapısı korunmaya özen gösterilir. Sonuç olarak yoğun kıvamlı, ipeksi dokulu ve karadutun kendine özgü lezzetini yansıtan geleneksel bir pekmez elde edilir. Karadutun Kendine Özgü Doğal Aroması Karadut, tatlı ve hafif ekşi lezzetin dengeli birleşimiyle öne çıkan özel bir meyvedir. PEKEFE Geleneksel İspir Karadut Pekmezi, bu karakteristik aromayı koruyacak şekilde üretilir. Yoğun meyve tadı, doğal rengi ve zengin aroması sayesinde kahvaltılardan özel tariflere kadar birçok kullanım alanında farkını hissettirir. Katkısız ve Güvenilir Üretim PEKEFE'nin doğallık anlayışı gereği ürünümüzde; İlave şeker bulunmaz. Glikoz şurubu kullanılmaz. Kimyasal koruyucu içermez. Yapay renklendirici içermez. Yapay aroma içermez. Karadutun doğal lezzeti ve geleneksel üretim anlayışı, ürünümüzün en önemli değeridir. Karadutun Doğal Zenginliği Karadut, doğal yapısında bulunan polifenoller ile dikkat çeken değerli bir meyvedir. Kontrollü üretim süreci sayesinde bu doğal bileşenlerin korunmasına özen gösterilir. PEKEFE Geleneksel İspir Karadut Pekmezi, doğal meyve içeriğiyle dengeli beslenmeyi tercih edenler için geleneksel ve katkısız bir alternatif sunar. Sofralarınıza Doğal Bir Lezzet Katın PEKEFE Geleneksel İspir Karadut Pekmezi; Kahvaltılarda, Tahin ile birlikte, Yoğurt ve sütle, Yulaf, granola ve müsli tariflerinde, Smoothie ve doğal içeceklerde, Tatlı ve hamur işi tariflerinde keyifle tüketilebilir. Yoğun aroması sayesinde az miktarda kullanıldığında bile tariflerinize zengin bir lezzet kazandırır. Neden PEKEFE? Çünkü PEKEFE, yalnızca ürün üretmez. İspir'in doğal zenginliklerini, üreticilerimizin emeğini ve geleneksel lezzet kültürünü geleceğe taşır. Her kavanozda; ✓ Özenle seçilmiş İspir karadutları, ✓ Kontrollü düşük sıcaklık üretimi, ✓ Katkısız içerik anlayışı, ✓ Modern hijyen standartları, ✓ Geleneksel üretim kültürüne duyulan saygı aynı titizlikle buluşur. PEKEFE – Doğadan Gelen Gerçek Karadut Lezzeti Şafak vakti özenle toplanan karadutlardan, besin değerlerini korumaya odaklanan kontrollü üretim süreciyle hazırlanan PEKEFE Geleneksel İspir Karadut Pekmezi , her kaşıkta İspir'in doğasını ve karadutun eşsiz aromasını hissettirir. Doğallığı, kaliteyi ve geleneksel üretim kültürünü bir araya getiren bu özel lezzet; kahvaltı sofralarından gurme tariflere kadar her anınıza değer katar. PEKEFE İspir'in Doğallığı, Gelenekten Gelen Lezzet.",
    "seoTitle": null,
    "seoDesc": null,
    "seoKeywords": null,
    "videoUrl": null,
    "attributes": {
      "shortDesc": "Düşük sıcaklıkta besin değerleri korunarak yoğunlaştırılmış, antioksidan zengini ve hafif ekşimsi aromasıyla öne çıkan premium yabani karadut özü.",
      "details": "Yabani karadut meyvelerinin şafak vakti hassasiyetle toplanıp preslenmesiyle elde edilen şıra, düşük sıcaklıktaki vakumlu kazanlarımızda besin değerlerini yitirmeden yoğunlaştırılır.\n\nKaradutun doğal ekşi-tatlı aroması ve yüksek polifenol yapısı korunur. Koruyucu, renklendirici ve ilave şeker barındırmayan bu özel mahsul, bağışıklık desteği ve doğal enerji deposudur.",
      "harvestStory": "Karadut meyvelerinin şafak vakti hassasiyetle toplanıp preslenmesiyle elde edilen şıra, düşük sıcaklıktaki vakumlu kazanlarımızda besin değerlerini yitirmeden yoğunlaştırılır.\n\nKaradutun doğal ekşi-tatlı aroması ve yüksek polifenol yapısı korunur. Koruyucu, renklendirici ve ilave şeker barındırmayan bu özel mahsul, bağışıklık desteği ve doğal enerji deposudur.",
      "ingredients": "%100 Yabani İspir Karadut Şırası",
      "ritual": "Sabahları aç karnına bir yemek kaşığı doğrudan tüketilmesi veya ılık kaynak suyuna eklenerek doğal bir şerbet şeklinde yavaşça yudumlanması önerilir.",
      "altitude": "1800 Metre",
      "harvestSeason": "Ağustos",
      "hmfLevel": "< 8 mg/kg (Analiz Raporlu)",
      "nutrients": {
        "energy": "285 kcal",
        "carb": "68.5 g",
        "protein": "1.2 g",
        "calcium": "380 mg",
        "iron": "12.4 mg"
      },
      "specifications": [
        {
          "key": "Menşei",
          "value": "Erzurum / İspir"
        },
        {
          "key": "Yoğunlaştırma Yöntemi",
          "value": "Düşük Sıcaklıkta Vakumlu Yoğunlaştırma"
        },
        {
          "key": "Katkı Maddesi",
          "value": "Sıfır (%100 Doğal)"
        },
        {
          "key": "Ambalaj",
          "value": "Premium Cam Şişe"
        }
      ],
      "barcode": "8692518542921",
      "unit": "Kg",
      "manufacturerCode": "PKF-PEK-4054",
      "stockType": "Ticari Mal",
      "warehouse": "Merkez Depo",
      "purchaseCurrency": "TRY",
      "purchaseVat": "1",
      "purchaseVatIncluded": false,
      "saleCurrency": "TRY",
      "saleVat": "1",
      "saleVatIncluded": true,
      "retailPrice": 1000,
      "retailCurrency": "TRY",
      "retailVat": "1",
      "retailVatIncluded": true,
      "webPrice": 1000,
      "webCurrency": "TRY",
      "webVat": "1",
      "webVatIncluded": true,
      "marketCurrency": "TRY",
      "marketVat": "1",
      "marketVatIncluded": true,
      "b2bActive": true,
      "b2bPreOrderable": false,
      "marketplaces": [
        {
          "id": "1",
          "name": "Trendyol API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "ty-api-90234892",
          "apiSecret": "••••••••",
          "logoColor": "bg-orange-500"
        },
        {
          "id": "2",
          "name": "Hepsiburada API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "hb-api-11029384",
          "apiSecret": "••••••••",
          "logoColor": "bg-red-600"
        },
        {
          "id": "3",
          "name": "Amazon Turkey API",
          "syncEnabled": false,
          "apiConnected": false,
          "logoColor": "bg-slate-500"
        }
      ],
      "recipeDetails": "",
      "unitCoefficients": [],
      "branchPrices": {},
      "specsMaterial": "",
      "specsWeight": "",
      "specsDimensions": "",
      "specsBellows": "",
      "usageGuide": "",
      "warrantyInfo": "",
      "warrantyBadgeLabel": "",
      "warrantyYears": "",
      "warrantyBadgeDesc": "",
      "quickOverview1_title": "",
      "quickOverview1_desc": "",
      "quickOverview2_title": "",
      "quickOverview2_desc": "",
      "quickOverview3_title": "",
      "quickOverview3_desc": "",
      "quickOverview1": "",
      "quickOverview2": "",
      "quickOverview3": "",
      "longDescExtra": "",
      "badgeText1": "",
      "badgeText2": "",
      "warehousePrices": {},
      "brand": "",
      "model": "",
      "sizes": [
        "400g Cam Kavanoz",
        "800g Cam Kavanoz",
        "1 kg Vakum",
        "5 kg Teneke",
        "850g Cam Kavanoz",
        "450g Cam Kavanoz",
        "1 Kg",
        "500 Gr"
      ],
      "colors": [
        "Sade",
        "Cevizli",
        "Fındıklı",
        "Antep Fıstıklı"
      ]
    },
    "isRawMaterial": false,
    "rating": 5,
    "reviews": 0,
    "isDeleted": false,
    "version": 1,
    "createdAt": "2026-08-09T12:26:58.996Z",
    "updatedAt": "2026-08-12T00:51:56.683Z",
    "companyId": null,
    "b2b_base_price": 0,
    "isDeal": false,
    "salesCount": 0,
    "variants": [],
    "locations": [
      {
        "id": "loc-merkez-cmsls1t84000hq1l0fcp06wcw",
        "productId": "cmsls1t84000hq1l0fcp06wcw",
        "productVariantId": null,
        "warehouseId": "1",
        "stock": 800,
        "reserved": 100,
        "minStock": 10,
        "criticalLimit": 15,
        "rack": "A-1",
        "warehouse": {
          "id": "1",
          "name": "İspir Üretim & Merkez Depo",
          "code": "WH-MRKZ",
          "type": "Merkez",
          "address": "Erzurum OSB, 3. Cadde",
          "isActive": true,
          "isLocked": false,
          "branchId": "default-branch",
          "companyId": null
        }
      }
    ],
    "recipe": [],
    "retail_list_price": 0,
    "discount_amount": 0,
    "discount_percent": 0,
    "saving_amount": 0,
    "is_discounted": false,
    "discount_display_text": "",
    "show_countdown": false,
    "server_time_utc": "2026-08-12T21:29:53.509Z",
    "b2b_price": null,
    "is_b2b_user": false,
    "volume_pricing_tiers": []
  },
  {
    "id": "cmsls1t7c000eq1l0x5o1n66b",
    "name": "PEKEFE İspir Dut Pekmezi",
    "sku": "PKF-650978",
    "category": "Pekmez ÇeşitLeri",
    "subCategory": null,
    "stock": 995,
    "criticalLimit": 5,
    "price": 800,
    "oldPrice": 850,
    "list_price": 0,
    "sale_price": 0,
    "discount_start_date": null,
    "discount_end_date": null,
    "stock_quantity": 0,
    "isCampaignActive": false,
    "cartDiscountRate": 0,
    "cost": 300,
    "image": "/uploads/1785870425901-o5xqxfpv2.webp",
    "images": [
      "/uploads/1785870425901-o5xqxfpv2.webp",
      "/uploads/1785870432153-vbtv3ryai.webp",
      "/uploads/1785870437692-leo3oj37x.webp",
      "/uploads/1785870451965-mpwiqeunl.webp",
      "/uploads/1785870907408-rssxnerh4.mp4",
      "/uploads/1785870457414-o4i2qgpee.webp"
    ],
    "desc": "PEKEFE Geleneksel İspir Dut Pekmezi İspir'in Asırlık Dut Ağaçlarından Gelen Saf Lezzet PEKEFE Geleneksel İspir Dut Pekmezi , Erzurum'un İspir ilçesinin yüksek oksijenli mikroklima vadilerinde yetişen asırlık beyaz dut ağaçlarının bereketli meyvelerinden üretilir. Dutlar, geleneksel hasat kültürünün en önemli uygulamalarından biri olan şafak vakti çarşaflar üzerine silkelenerek özenle toplanır. Böylece yere temas etmeyen, en doğal ve olgun meyveler seçilerek üretime alınır. PEKEFE için bu süreç yalnızca bir hasat değil; doğaya, emeğe ve İspir'in köklü üretim geleneğine duyulan saygının ilk adımıdır. Geleneksel Bakır Kazanlarda Ustalıkla Hazırlanır Toplanan dutlardan elde edilen saf dut şırası, nesiller boyunca sürdürülen geleneksel yöntemlere bağlı kalınarak bakır kazanlarda (herle) ve meşe odunu ateşinde ağır ağır pişirilir. Yavaş ve kontrollü pişirme süreci, dutun doğal aromasının, kendine özgü renginin ve yoğun kıvamının korunmasına yardımcı olur. Bu geleneksel yöntem sayesinde ortaya çıkan pekmez; ipeksi dokusu, zengin aroması ve dengeli lezzetiyle İspir'in gerçek pekmez kültürünü yansıtır. Doğallığını Koruyan Üretim Anlayışı PEKEFE Geleneksel İspir Dut Pekmezi'nin üretiminde doğallık temel prensiptir. Ürünümüz; İlave şeker içermez. Glikoz şurubu içermez. Kimyasal koruyucu içermez. Yapay renklendirici içermez. Yapay tatlandırıcı içermez. Sadece dutun kendi doğal lezzeti ve geleneksel üretim ustalığıyla hazırlanır. Kaliteyi Koruyan Kontrollü Üretim Üretim sürecinde pekmez, HMF (Hidroksimetilfurfural) oluşumunun kontrol altında tutulmasına özen gösterilerek uygun sıcaklıklarda dinlendirilir. Böylece ürünün doğal karakteri korunurken kalite standartlarının sürdürülebilirliği de desteklenir. PEKEFE'nin üretim anlayışı; geleneksel yöntemleri modern kalite ve hijyen uygulamalarıyla birleştirerek her kavanozda aynı güveni sunmayı hedefler. Dutun Doğal Aromasını Hissettiren Eşsiz Tat İspir'in iklimi ve verimli topraklarının kazandırdığı karakter sayesinde PEKEFE Geleneksel İspir Dut Pekmezi; Yoğun kıvamı, İpeksi dokusu, Dutun kendi doğal karamelize aroması, Kendine özgü zengin lezzeti ile kahvaltı sofralarından geleneksel tariflere kadar her kullanımda farkını hissettirir. Sofralarınıza Gelen Doğal Miras PEKEFE Geleneksel İspir Dut Pekmezi; Kahvaltılarda tahin ile birlikte, Yoğurt ve sütle, Yulaf ve granola tariflerinde, Tatlı yapımında, Geleneksel lezzetleri modern tariflerle buluşturmak isteyenler için doğal ve eşsiz bir seçimdir. Neden PEKEFE? Çünkü PEKEFE, yalnızca pekmez üretmez. İspir'in bereketli vadilerini, asırlık dut ağaçlarını, geleneksel bakır kazanlarını ve ustaların yıllara dayanan emeğini her kavanoza özenle taşır. Her ürünümüzde; ✓ İspir'in üretim kültürüne bağlılık, ✓ Doğal hammaddelere duyulan saygı, ✓ Geleneksel yöntemlerin korunması, ✓ Modern hijyen ve kalite standartları, ✓ Katkısız ve güvenilir üretim anlayışı aynı titizlikle yaşatılır. PEKEFE – İspir'in Doğallığını Sofralarınıza Taşıyoruz Şafak vakti toplanan beyaz dutlardan, meşe odunu ateşinde ağır ağır pişirilen geleneksel bakır kazanlara uzanan bu yolculuk; her kaşıkta İspir'in doğasını, emeğini ve köklü lezzet mirasını hissettirir. PEKEFE Geleneksel İspir Dut Pekmezi , yalnızca bir pekmez değil; Anadolu'nun kadim üretim kültürünün, doğallığın ve ustalığın sofralarınıza ulaşan en değerli temsilcisidir. PEKEFE İspir'in Doğallığı, Gelenekten Gelen Lezzet.",
    "seoTitle": null,
    "seoDesc": null,
    "seoKeywords": null,
    "videoUrl": null,
    "attributes": {
      "shortDesc": "İspir’in 2000 metre rakımlı yaylalarındaki asırlık beyaz dut ağaçlarından toplanan, bakır kazanlarda odun ateşinde ağır ağır kaynatılmış %100 saf ve katkısız geleneksel dut pekmezi.",
      "details": "PEKEFE Geleneksel İspir Dut Pekmezi, Erzurum İspir’in yüksek oksijenli mikroklimal vadilerinde yetişen asırlık beyaz dut ağaçlarından şafak vakti çarşaflar serilerek el emeğiyle toplanan saf meyvelerden üretilir.\n\nHiçbir kimyasal koruyucu, tatlandırıcı, renklendirici veya glikoz şurubu içermeyen doğal dut şırası, geleneksel bakır kazanlarda (herle) meşe odunu ateşinde kıvam alıncaya kadar ağır ağır pişirilir.\n\nHMF değerlerinin yükselmemesi için ideal sıcaklıklarda dinlendirilen pekmezimiz, kimyasal koruyucu ve ilave şeker barındırmaz. İpeksi dokusu ve meyvenin kendi doğal karamelize aromasıyla mineral deposu bir geleneksel lezzet şölenidir.",
      "harvestStory": "PEKEFE Geleneksel İspir Dut Pekmezi, Erzurum İspir’in yüksek oksijenli mikroklimal vadilerinde yetişen asırlık beyaz dut ağaçlarından şafak vakti çarşaflar serilerek el emeğiyle toplanan saf meyvelerden üretilir.\n\nHiçbir kimyasal koruyucu, tatlandırıcı, renklendirici veya glikoz şurubu içermeyen doğal dut şırası, geleneksel bakır kazanlarda (herle) meşe odunu ateşinde kıvam alıncaya kadar ağır ağır pişirilir.\n\nHMF değerlerinin yükselmemesi için ideal sıcaklıklarda dinlendirilen pekmezimiz, kimyasal koruyucu ve ilave şeker barındırmaz. İpeksi dokusu ve meyvenin kendi doğal karamelize aromasıyla mineral deposu bir geleneksel lezzet şölenidir.",
      "ingredients": "%100 Saf İspir Beyaz Dut Şırası",
      "ritual": "Oda sıcaklığında (18°C - 22°C), taş değirmen tahini ile %40’a %60 oranında karıştırılarak servis edilmesi önerilir. Karıştırırken ahşap veya seramik kaşık tercih edilmelidir.",
      "altitude": "2200 Metre",
      "harvestSeason": "Temmuz - Ağustos",
      "hmfLevel": "< 10 mg/kg (Analiz Raporlu)",
      "nutrients": {
        "energy": "293 kcal",
        "carb": "70.2 g",
        "protein": "0.8 g",
        "calcium": "400 mg",
        "iron": "10.2 mg"
      },
      "specifications": [
        {
          "key": "Menşei",
          "value": "Erzurum / İspir"
        },
        {
          "key": "Pişirme Yöntemi",
          "value": "Odun Ateşinde Bakır Kazanlar"
        },
        {
          "key": "Şeker İlavesi",
          "value": "0.0% (Sadece Doğal Meyve Şekeri)"
        },
        {
          "key": "HMF Seviyesi",
          "value": "< 10 mg/kg (Analiz Raporlu)"
        }
      ],
      "barcode": "8697430273549",
      "unit": "Kg",
      "manufacturerCode": "PKF-PEK-5106",
      "stockType": "Ticari Mal",
      "warehouse": "Merkez Depo",
      "purchaseCurrency": "TRY",
      "purchaseVat": "1",
      "purchaseVatIncluded": true,
      "saleCurrency": "TRY",
      "saleVat": "1",
      "saleVatIncluded": true,
      "retailPrice": 800,
      "retailCurrency": "TRY",
      "retailVat": "1",
      "retailVatIncluded": true,
      "webPrice": 800,
      "webCurrency": "TRY",
      "webVat": "1",
      "webVatIncluded": true,
      "marketCurrency": "TRY",
      "marketVat": "1",
      "marketVatIncluded": true,
      "b2bActive": true,
      "b2bPreOrderable": false,
      "marketplaces": [
        {
          "id": "1",
          "name": "Trendyol API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "ty-api-90234892",
          "apiSecret": "••••••••",
          "logoColor": "bg-orange-500"
        },
        {
          "id": "2",
          "name": "Hepsiburada API",
          "syncEnabled": true,
          "apiConnected": true,
          "apiKey": "hb-api-11029384",
          "apiSecret": "••••••••",
          "logoColor": "bg-red-600"
        },
        {
          "id": "3",
          "name": "Amazon Turkey API",
          "syncEnabled": false,
          "apiConnected": false,
          "logoColor": "bg-slate-500"
        }
      ],
      "recipeDetails": "",
      "unitCoefficients": [],
      "branchPrices": {},
      "specsMaterial": "",
      "specsWeight": "",
      "specsDimensions": "",
      "specsBellows": "",
      "usageGuide": "",
      "warrantyInfo": "",
      "warrantyBadgeLabel": "",
      "warrantyYears": "",
      "warrantyBadgeDesc": "",
      "quickOverview1_title": "",
      "quickOverview1_desc": "",
      "quickOverview2_title": "",
      "quickOverview2_desc": "",
      "quickOverview3_title": "",
      "quickOverview3_desc": "",
      "quickOverview1": "",
      "quickOverview2": "",
      "quickOverview3": "",
      "longDescExtra": "",
      "badgeText1": "",
      "badgeText2": "",
      "warehousePrices": {},
      "brand": "",
      "model": "",
      "sizes": [
        "400g Cam Kavanoz",
        "800g Cam Kavanoz",
        "1 kg Vakum",
        "5 kg Teneke",
        "850g Cam Kavanoz",
        "450g Cam Kavanoz",
        "1 Kg",
        "500 Gr"
      ],
      "colors": [
        "Sade",
        "Cevizli",
        "Fındıklı",
        "Antep Fıstıklı"
      ]
    },
    "isRawMaterial": false,
    "rating": 5,
    "reviews": 0,
    "isDeleted": false,
    "version": 1,
    "createdAt": "2026-08-09T12:26:58.968Z",
    "updatedAt": "2026-08-12T00:51:56.683Z",
    "companyId": null,
    "b2b_base_price": 0,
    "isDeal": false,
    "salesCount": 0,
    "variants": [],
    "locations": [
      {
        "id": "loc-merkez-cmsls1t7c000eq1l0x5o1n66b",
        "productId": "cmsls1t7c000eq1l0x5o1n66b",
        "productVariantId": null,
        "warehouseId": "1",
        "stock": 796,
        "reserved": 100,
        "minStock": 5,
        "criticalLimit": 8,
        "rack": "A-1",
        "warehouse": {
          "id": "1",
          "name": "İspir Üretim & Merkez Depo",
          "code": "WH-MRKZ",
          "type": "Merkez",
          "address": "Erzurum OSB, 3. Cadde",
          "isActive": true,
          "isLocked": false,
          "branchId": "default-branch",
          "companyId": null
        }
      }
    ],
    "recipe": [],
    "retail_list_price": 0,
    "discount_amount": 0,
    "discount_percent": 0,
    "saving_amount": 0,
    "is_discounted": false,
    "discount_display_text": "",
    "show_countdown": false,
    "server_time_utc": "2026-08-12T21:29:53.509Z",
    "b2b_price": null,
    "is_b2b_user": false,
    "volume_pricing_tiers": []
  }
];
