
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.CompanyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  taxNo: 'taxNo',
  taxOffice: 'taxOffice',
  domain: 'domain',
  currency: 'currency',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  expires_at: 'expires_at',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId',
  expires: 'expires'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  password: 'password',
  role: 'role',
  isApproved: 'isApproved',
  isDeleted: 'isDeleted',
  companyId: 'companyId',
  branchId: 'branchId',
  warehouseId: 'warehouseId',
  customer_type: 'customer_type',
  b2b_group_id: 'b2b_group_id',
  company_name: 'company_name',
  tax_id: 'tax_id',
  tax_office: 'tax_office',
  credit_limit: 'credit_limit',
  current_balance: 'current_balance'
};

exports.Prisma.VerificationTokenScalarFieldEnum = {
  identifier: 'identifier',
  token: 'token',
  expires: 'expires'
};

exports.Prisma.AddressScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  addressTitle: 'addressTitle',
  firstName: 'firstName',
  lastName: 'lastName',
  phone: 'phone',
  city: 'city',
  district: 'district',
  fullAddress: 'fullAddress',
  isDefault: 'isDefault'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  name: 'name',
  sku: 'sku',
  category: 'category',
  subCategory: 'subCategory',
  stock: 'stock',
  criticalLimit: 'criticalLimit',
  price: 'price',
  oldPrice: 'oldPrice',
  list_price: 'list_price',
  sale_price: 'sale_price',
  discount_start_date: 'discount_start_date',
  discount_end_date: 'discount_end_date',
  stock_quantity: 'stock_quantity',
  isCampaignActive: 'isCampaignActive',
  cartDiscountRate: 'cartDiscountRate',
  cost: 'cost',
  image: 'image',
  images: 'images',
  desc: 'desc',
  seoTitle: 'seoTitle',
  seoDesc: 'seoDesc',
  seoKeywords: 'seoKeywords',
  videoUrl: 'videoUrl',
  attributes: 'attributes',
  isRawMaterial: 'isRawMaterial',
  rating: 'rating',
  reviews: 'reviews',
  isDeleted: 'isDeleted',
  version: 'version',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  companyId: 'companyId',
  b2b_base_price: 'b2b_base_price',
  isDeal: 'isDeal',
  salesCount: 'salesCount'
};

exports.Prisma.CategoryDetailScalarFieldEnum = {
  id: 'id',
  name: 'name',
  parentId: 'parentId',
  attributes: 'attributes',
  variants: 'variants'
};

exports.Prisma.ProductVariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  attributes: 'attributes',
  stock: 'stock',
  price: 'price',
  sku: 'sku',
  barcode: 'barcode',
  cost: 'cost'
};

exports.Prisma.StockLocationScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  productVariantId: 'productVariantId',
  warehouseId: 'warehouseId',
  stock: 'stock',
  reserved: 'reserved',
  minStock: 'minStock',
  criticalLimit: 'criticalLimit',
  rack: 'rack'
};

exports.Prisma.WarehouseScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  type: 'type',
  address: 'address',
  isActive: 'isActive',
  isLocked: 'isLocked',
  branchId: 'branchId',
  companyId: 'companyId'
};

exports.Prisma.BranchScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  address: 'address',
  phone: 'phone',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RecipeItemScalarFieldEnum = {
  id: 'id',
  mainProductId: 'mainProductId',
  mainProductVariantId: 'mainProductVariantId',
  ingredientId: 'ingredientId',
  ingredientVariantId: 'ingredientVariantId',
  quantity: 'quantity',
  unit: 'unit'
};

exports.Prisma.ProductionOrderScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  productVariantId: 'productVariantId',
  quantity: 'quantity',
  status: 'status',
  date: 'date',
  startDate: 'startDate',
  endDate: 'endDate',
  productionPlanId: 'productionPlanId',
  warehouseId: 'warehouseId',
  approvedBy: 'approvedBy',
  completedBy: 'completedBy',
  notes: 'notes',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CurrentAccountScalarFieldEnum = {
  id: 'id',
  cariKod: 'cariKod',
  name: 'name',
  type: 'type',
  cariTipi: 'cariTipi',
  ad: 'ad',
  soyad: 'soyad',
  tckn: 'tckn',
  dogumTarihi: 'dogumTarihi',
  taxNo: 'taxNo',
  taxId: 'taxId',
  taxOffice: 'taxOffice',
  mersisNo: 'mersisNo',
  yetkiliKisi: 'yetkiliKisi',
  webSitesi: 'webSitesi',
  phone: 'phone',
  email: 'email',
  address: 'address',
  balance: 'balance',
  currency: 'currency',
  openingBalance: 'openingBalance',
  isActive: 'isActive',
  isDeleted: 'isDeleted',
  discountRate: 'discountRate',
  creditLimit: 'creditLimit',
  riskLimit: 'riskLimit',
  vadeGun: 'vadeGun',
  b2bMinQty: 'b2bMinQty',
  b2bPaymentTerms: 'b2bPaymentTerms',
  b2bCode: 'b2bCode',
  loyaltyPoints: 'loyaltyPoints',
  dealerGroup: 'dealerGroup',
  priceGroup: 'priceGroup',
  priceFormula: 'priceFormula',
  parentDealerId: 'parentDealerId',
  kaynakPlatform: 'kaynakPlatform',
  eFaturaDurumu: 'eFaturaDurumu',
  blokeDurumu: 'blokeDurumu',
  adresler: 'adresler',
  entegrasyonHaritalama: 'entegrasyonHaritalama',
  auditLogs: 'auditLogs',
  dosyalar: 'dosyalar',
  bankalar: 'bankalar',
  kvkk: 'kvkk',
  yetkililer: 'yetkililer',
  tanimlar: 'tanimlar',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  companyId: 'companyId'
};

exports.Prisma.SubAccountScalarFieldEnum = {
  id: 'id',
  currentAccountId: 'currentAccountId',
  name: 'name',
  email: 'email',
  phone: 'phone',
  role: 'role',
  balance: 'balance'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  currentAccountId: 'currentAccountId',
  subAccountId: 'subAccountId',
  date: 'date',
  type: 'type',
  amount: 'amount',
  description: 'description',
  paymentMethod: 'paymentMethod'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  currentAccountId: 'currentAccountId',
  date: 'date',
  dueDate: 'dueDate',
  totalAmount: 'totalAmount',
  taxAmount: 'taxAmount',
  status: 'status',
  type: 'type',
  externalLink: 'externalLink',
  items: 'items',
  notes: 'notes',
  isDeleted: 'isDeleted',
  stockMovement: 'stockMovement',
  companyId: 'companyId'
};

exports.Prisma.BankScalarFieldEnum = {
  id: 'id',
  name: 'name',
  accountNumber: 'accountNumber',
  iban: 'iban',
  balance: 'balance',
  currency: 'currency',
  logo: 'logo',
  branch: 'branch',
  type: 'type'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  currentAccountId: 'currentAccountId',
  date: 'date',
  status: 'status',
  total: 'total',
  shippingFee: 'shippingFee',
  summary: 'summary',
  type: 'type',
  method: 'method',
  isDeleted: 'isDeleted',
  companyId: 'companyId'
};

exports.Prisma.CMSDataScalarFieldEnum = {
  id: 'id',
  heroTitle: 'heroTitle',
  heroSubtitle: 'heroSubtitle',
  buttonText: 'buttonText',
  announcement: 'announcement',
  announcement2: 'announcement2',
  maintenanceMode: 'maintenanceMode',
  siteName: 'siteName',
  primaryColor: 'primaryColor',
  secondaryColor: 'secondaryColor',
  siteDescription: 'siteDescription',
  categoryTitle: 'categoryTitle',
  categorySubtitle: 'categorySubtitle',
  appTitle: 'appTitle',
  appSubtitle: 'appSubtitle',
  contactPhone: 'contactPhone',
  contactEmail: 'contactEmail',
  contactAddress: 'contactAddress',
  socialInstagram: 'socialInstagram',
  socialWhatsapp: 'socialWhatsapp',
  socialFacebook: 'socialFacebook',
  socialYoutube: 'socialYoutube',
  logoFont: 'logoFont',
  logoUrl: 'logoUrl',
  logoSize: 'logoSize',
  logoWeight: 'logoWeight',
  footerSlogan: 'footerSlogan',
  borderRadius: 'borderRadius',
  announcementActive: 'announcementActive',
  announcementSpeed: 'announcementSpeed',
  layoutWidth: 'layoutWidth',
  heroAlignment: 'heroAlignment',
  pricingRules: 'pricingRules',
  shippingThreshold: 'shippingThreshold',
  shippingFee: 'shippingFee',
  shippingCarriers: 'shippingCarriers',
  themeTemplates: 'themeTemplates',
  contentAnywhereRules: 'contentAnywhereRules',
  savedSectionTemplates: 'savedSectionTemplates',
  popupConfig: 'popupConfig',
  topBarText1: 'topBarText1',
  topBarText2: 'topBarText2',
  faqData: 'faqData',
  cartDiscountType: 'cartDiscountType',
  cartDiscountValue: 'cartDiscountValue',
  cartDiscountMinAmount: 'cartDiscountMinAmount',
  bankTransferDiscountRate: 'bankTransferDiscountRate',
  companyName: 'companyName',
  bankName: 'bankName',
  bankIban: 'bankIban',
  efaturaPrefix: 'efaturaPrefix',
  earsivPrefix: 'earsivPrefix',
  companyStampUrl: 'companyStampUrl',
  companyOwnerName: 'companyOwnerName',
  companyOwnerSurname: 'companyOwnerSurname',
  companyTaxNo: 'companyTaxNo',
  companyTaxOffice: 'companyTaxOffice',
  companyFax: 'companyFax',
  companyGsm: 'companyGsm',
  companyKepAddress: 'companyKepAddress',
  companyMersisNo: 'companyMersisNo',
  companySicilNo: 'companySicilNo',
  companyRegion: 'companyRegion',
  companyCountry: 'companyCountry',
  companyCity: 'companyCity',
  companyDistrict: 'companyDistrict',
  companyBuildingName: 'companyBuildingName',
  companyBuildingNo: 'companyBuildingNo',
  companyStreet: 'companyStreet',
  companyPostalCode: 'companyPostalCode',
  companyWebsite: 'companyWebsite',
  companyDefaultKdv: 'companyDefaultKdv',
  companyDefaultUnit: 'companyDefaultUnit',
  companyDefaultReturnDays: 'companyDefaultReturnDays',
  companySalesKdvIncluded: 'companySalesKdvIncluded',
  companyPurchaseKdvIncluded: 'companyPurchaseKdvIncluded',
  companyDefaultLanguages: 'companyDefaultLanguages',
  companyExcludedChars: 'companyExcludedChars',
  companyDefaultTevkifatCode: 'companyDefaultTevkifatCode',
  companyListStartDay: 'companyListStartDay',
  companyAutoSendEarsivMail: 'companyAutoSendEarsivMail',
  companyUsePaymentPlan: 'companyUsePaymentPlan',
  companyAutoUpdatePriceByMargin: 'companyAutoUpdatePriceByMargin',
  companyUseCurrencyInPurchase: 'companyUseCurrencyInPurchase',
  companyAutoDeductInstallments: 'companyAutoDeductInstallments',
  companyUseRowRateInPurchase: 'companyUseRowRateInPurchase',
  companyCheckCurrentVkn: 'companyCheckCurrentVkn',
  companyInvoiceFooter: 'companyInvoiceFooter',
  footerText: 'footerText',
  mapCoordinates: 'mapCoordinates',
  dealSectionActive: 'dealSectionActive',
  dealProductIds: 'dealProductIds',
  paymentMethodsConfig: 'paymentMethodsConfig',
  paytrConfig: 'paytrConfig',
  installmentsConfig: 'installmentsConfig',
  cashOnDeliveryFee: 'cashOnDeliveryFee',
  cashOnDeliveryEnabled: 'cashOnDeliveryEnabled',
  minOrderAmountForOpenAccount: 'minOrderAmountForOpenAccount',
  openAccountDaysLimit: 'openAccountDaysLimit'
};

exports.Prisma.CMSPageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  status: 'status',
  sections: 'sections',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.IntegrationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  status: 'status',
  lastSync: 'lastSync',
  logo: 'logo',
  settings: 'settings'
};

exports.Prisma.IntegrationLogScalarFieldEnum = {
  id: 'id',
  integrationId: 'integrationId',
  time: 'time',
  message: 'message',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.StockTransactionScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  productVariantId: 'productVariantId',
  warehouseId: 'warehouseId',
  type: 'type',
  quantity: 'quantity',
  unitCost: 'unitCost',
  remainingQty: 'remainingQty',
  description: 'description',
  date: 'date',
  userId: 'userId',
  userEmail: 'userEmail',
  moduleSource: 'moduleSource',
  ipAddress: 'ipAddress',
  referenceId: 'referenceId',
  metadata: 'metadata',
  companyId: 'companyId'
};

exports.Prisma.StockTransferScalarFieldEnum = {
  id: 'id',
  transferNo: 'transferNo',
  productId: 'productId',
  fromWarehouseId: 'fromWarehouseId',
  toWarehouseId: 'toWarehouseId',
  quantity: 'quantity',
  status: 'status',
  requester: 'requester',
  approvedBy: 'approvedBy',
  rejectionReason: 'rejectionReason',
  notes: 'notes',
  dispatchedAt: 'dispatchedAt',
  receivedAt: 'receivedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockCycleCountScalarFieldEnum = {
  id: 'id',
  code: 'code',
  warehouseId: 'warehouseId',
  type: 'type',
  status: 'status',
  isLocked: 'isLocked',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  notes: 'notes',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockCycleCountItemScalarFieldEnum = {
  id: 'id',
  cycleCountId: 'cycleCountId',
  productId: 'productId',
  systemStock: 'systemStock',
  countedStock: 'countedStock',
  difference: 'difference',
  rack: 'rack',
  notes: 'notes'
};

exports.Prisma.CouponScalarFieldEnum = {
  id: 'id',
  code: 'code',
  discountType: 'discountType',
  discountValue: 'discountValue',
  minCartAmount: 'minCartAmount',
  maxUses: 'maxUses',
  uses: 'uses',
  isActive: 'isActive',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
};

exports.Prisma.TicketScalarFieldEnum = {
  id: 'id',
  email: 'email',
  subject: 'subject',
  status: 'status',
  category: 'category',
  orderId: 'orderId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TicketMessageScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  sender: 'sender',
  message: 'message',
  createdAt: 'createdAt'
};

exports.Prisma.CampaignScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  type: 'type',
  value: 'value',
  minOrder: 'minOrder',
  maxUses: 'maxUses',
  usedCount: 'usedCount',
  startDate: 'startDate',
  endDate: 'endDate',
  isActive: 'isActive',
  target: 'target',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FeedbackScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  rating: 'rating',
  message: 'message',
  status: 'status',
  reply: 'reply',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BlogPostScalarFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  content: 'content',
  category: 'category',
  image: 'image',
  metaDesc: 'metaDesc',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountingAccountScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  type: 'type',
  parentCode: 'parentCode',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.JournalEntryScalarFieldEnum = {
  id: 'id',
  date: 'date',
  number: 'number',
  description: 'description',
  status: 'status',
  type: 'type',
  createdBy: 'createdBy',
  referenceId: 'referenceId',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.JournalLineScalarFieldEnum = {
  id: 'id',
  journalEntryId: 'journalEntryId',
  debitAccountId: 'debitAccountId',
  creditAccountId: 'creditAccountId',
  amount: 'amount',
  description: 'description'
};

exports.Prisma.ExpenseScalarFieldEnum = {
  id: 'id',
  date: 'date',
  category: 'category',
  amount: 'amount',
  taxAmount: 'taxAmount',
  description: 'description',
  supplier: 'supplier',
  receiptNo: 'receiptNo',
  paymentMethod: 'paymentMethod',
  bankId: 'bankId',
  status: 'status',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BudgetItemScalarFieldEnum = {
  id: 'id',
  year: 'year',
  month: 'month',
  category: 'category',
  planned: 'planned',
  actual: 'actual',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TaxDeclarationScalarFieldEnum = {
  id: 'id',
  period: 'period',
  type: 'type',
  amount: 'amount',
  taxBase: 'taxBase',
  taxRate: 'taxRate',
  status: 'status',
  dueDate: 'dueDate',
  paidDate: 'paidDate',
  paidAt: 'paidAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.InvoiceItemScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  name: 'name',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  vatRate: 'vatRate',
  totalAmount: 'totalAmount'
};

exports.Prisma.IncomeScalarFieldEnum = {
  id: 'id',
  date: 'date',
  category: 'category',
  amount: 'amount',
  taxAmount: 'taxAmount',
  description: 'description',
  currentAccountId: 'currentAccountId',
  paymentMethod: 'paymentMethod',
  bankId: 'bankId',
  status: 'status',
  companyId: 'companyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuthLogScalarFieldEnum = {
  id: 'id',
  ip: 'ip',
  userId: 'userId',
  route: 'route',
  method: 'method',
  failReason: 'failReason',
  createdAt: 'createdAt'
};

exports.Prisma.MediaItemScalarFieldEnum = {
  id: 'id',
  name: 'name',
  url: 'url',
  size: 'size',
  tag: 'tag',
  alt: 'alt',
  createdAt: 'createdAt'
};

exports.Prisma.ProductUnitScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  factor: 'factor',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductionPlanScalarFieldEnum = {
  id: 'id',
  name: 'name',
  startDate: 'startDate',
  endDate: 'endDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkstationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  capacity: 'capacity',
  unit: 'unit',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RouteStepScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  stepNumber: 'stepNumber',
  name: 'name',
  workstationId: 'workstationId',
  setupTime: 'setupTime',
  runTime: 'runTime',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WasteLogScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  productVariantId: 'productVariantId',
  productionOrderId: 'productionOrderId',
  warehouseId: 'warehouseId',
  quantity: 'quantity',
  reason: 'reason',
  date: 'date',
  createdAt: 'createdAt'
};

exports.Prisma.PurchaseRequisitionScalarFieldEnum = {
  id: 'id',
  requisitionNo: 'requisitionNo',
  requestDate: 'requestDate',
  branchId: 'branchId',
  departmentId: 'departmentId',
  requesterId: 'requesterId',
  projectId: 'projectId',
  costCenterId: 'costCenterId',
  priority: 'priority',
  status: 'status',
  approvalStatus: 'approvalStatus',
  expectedDeliveryDate: 'expectedDeliveryDate',
  totalAmount: 'totalAmount',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PurchaseRequisitionItemScalarFieldEnum = {
  id: 'id',
  requisitionId: 'requisitionId',
  productId: 'productId',
  warehouseId: 'warehouseId',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice',
  description: 'description'
};

exports.Prisma.PurchaseRequisitionApprovalScalarFieldEnum = {
  id: 'id',
  requisitionId: 'requisitionId',
  approverId: 'approverId',
  action: 'action',
  comment: 'comment',
  approvalDate: 'approvalDate'
};

exports.Prisma.DespatchAdviceScalarFieldEnum = {
  id: 'id',
  despatchNo: 'despatchNo',
  ettnNo: 'ettnNo',
  customerAccountId: 'customerAccountId',
  invoiceId: 'invoiceId',
  orderId: 'orderId',
  issueDate: 'issueDate',
  actualDespatchDate: 'actualDespatchDate',
  carrierId: 'carrierId',
  driverName: 'driverName',
  driverIdentityNo: 'driverIdentityNo',
  licensePlate: 'licensePlate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DespatchLineScalarFieldEnum = {
  id: 'id',
  despatchId: 'despatchId',
  productId: 'productId',
  quantity: 'quantity',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.PermissionScalarFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  roleId: 'roleId',
  permissionId: 'permissionId'
};

exports.Prisma.UserRoleScalarFieldEnum = {
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.SystemAuditLogScalarFieldEnum = {
  id: 'id',
  tableName: 'tableName',
  recordId: 'recordId',
  action: 'action',
  oldData: 'oldData',
  newData: 'newData',
  userId: 'userId',
  companyId: 'companyId',
  createdAt: 'createdAt'
};

exports.Prisma.B2BGroupScalarFieldEnum = {
  id: 'id',
  group_name: 'group_name',
  base_discount_rate: 'base_discount_rate',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductB2BPriceScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  b2bGroupId: 'b2bGroupId',
  price: 'price'
};

exports.Prisma.TieredPricingScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  b2bGroupId: 'b2bGroupId',
  min_quantity: 'min_quantity',
  discount_percentage: 'discount_percentage'
};

exports.Prisma.AdminNotificationScalarFieldEnum = {
  id: 'id',
  title: 'title',
  message: 'message',
  type: 'type',
  isRead: 'isRead',
  createdAt: 'createdAt',
  orderId: 'orderId'
};

exports.Prisma.FeatureModuleScalarFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  description: 'description',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CompanyPermissionScalarFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  featureModuleId: 'featureModuleId',
  isEnabled: 'isEnabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FailedCargoRequestScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  carrierName: 'carrierName',
  requestPayload: 'requestPayload',
  errorMessage: 'errorMessage',
  retryCount: 'retryCount',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.EmailTemplateScalarFieldEnum = {
  id: 'id',
  eventType: 'eventType',
  name: 'name',
  subject: 'subject',
  bodyHtml: 'bodyHtml',
  variables: 'variables',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.EmailLogScalarFieldEnum = {
  id: 'id',
  recipient: 'recipient',
  subject: 'subject',
  bodyHtml: 'bodyHtml',
  eventType: 'eventType',
  status: 'status',
  errorMessage: 'errorMessage',
  retryCount: 'retryCount',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.CompanyOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  taxNo: 'taxNo',
  taxOffice: 'taxOffice',
  domain: 'domain',
  currency: 'currency'
};

exports.Prisma.AccountOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  provider: 'provider',
  providerAccountId: 'providerAccountId',
  refresh_token: 'refresh_token',
  access_token: 'access_token',
  token_type: 'token_type',
  scope: 'scope',
  id_token: 'id_token',
  session_state: 'session_state'
};

exports.Prisma.SessionOrderByRelevanceFieldEnum = {
  id: 'id',
  sessionToken: 'sessionToken',
  userId: 'userId'
};

exports.Prisma.UserOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  image: 'image',
  password: 'password',
  role: 'role',
  companyId: 'companyId',
  branchId: 'branchId',
  warehouseId: 'warehouseId',
  customer_type: 'customer_type',
  b2b_group_id: 'b2b_group_id',
  company_name: 'company_name',
  tax_id: 'tax_id',
  tax_office: 'tax_office'
};

exports.Prisma.VerificationTokenOrderByRelevanceFieldEnum = {
  identifier: 'identifier',
  token: 'token'
};

exports.Prisma.AddressOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  addressTitle: 'addressTitle',
  firstName: 'firstName',
  lastName: 'lastName',
  phone: 'phone',
  city: 'city',
  district: 'district',
  fullAddress: 'fullAddress'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.ProductOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  sku: 'sku',
  category: 'category',
  subCategory: 'subCategory',
  image: 'image',
  desc: 'desc',
  seoTitle: 'seoTitle',
  seoDesc: 'seoDesc',
  seoKeywords: 'seoKeywords',
  videoUrl: 'videoUrl',
  companyId: 'companyId'
};

exports.Prisma.CategoryDetailOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  parentId: 'parentId'
};

exports.Prisma.ProductVariantOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  sku: 'sku',
  barcode: 'barcode'
};

exports.Prisma.StockLocationOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  productVariantId: 'productVariantId',
  warehouseId: 'warehouseId',
  rack: 'rack'
};

exports.Prisma.WarehouseOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  type: 'type',
  address: 'address',
  branchId: 'branchId',
  companyId: 'companyId'
};

exports.Prisma.BranchOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  address: 'address',
  phone: 'phone'
};

exports.Prisma.RecipeItemOrderByRelevanceFieldEnum = {
  id: 'id',
  mainProductId: 'mainProductId',
  mainProductVariantId: 'mainProductVariantId',
  ingredientId: 'ingredientId',
  ingredientVariantId: 'ingredientVariantId',
  unit: 'unit'
};

exports.Prisma.ProductionOrderOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  productVariantId: 'productVariantId',
  status: 'status',
  productionPlanId: 'productionPlanId',
  warehouseId: 'warehouseId',
  approvedBy: 'approvedBy',
  completedBy: 'completedBy',
  notes: 'notes',
  companyId: 'companyId'
};

exports.Prisma.CurrentAccountOrderByRelevanceFieldEnum = {
  id: 'id',
  cariKod: 'cariKod',
  name: 'name',
  type: 'type',
  cariTipi: 'cariTipi',
  ad: 'ad',
  soyad: 'soyad',
  tckn: 'tckn',
  taxNo: 'taxNo',
  taxId: 'taxId',
  taxOffice: 'taxOffice',
  mersisNo: 'mersisNo',
  yetkiliKisi: 'yetkiliKisi',
  webSitesi: 'webSitesi',
  phone: 'phone',
  email: 'email',
  address: 'address',
  currency: 'currency',
  b2bPaymentTerms: 'b2bPaymentTerms',
  b2bCode: 'b2bCode',
  dealerGroup: 'dealerGroup',
  priceGroup: 'priceGroup',
  priceFormula: 'priceFormula',
  parentDealerId: 'parentDealerId',
  kaynakPlatform: 'kaynakPlatform',
  companyId: 'companyId'
};

exports.Prisma.SubAccountOrderByRelevanceFieldEnum = {
  id: 'id',
  currentAccountId: 'currentAccountId',
  name: 'name',
  email: 'email',
  phone: 'phone',
  role: 'role'
};

exports.Prisma.TransactionOrderByRelevanceFieldEnum = {
  id: 'id',
  currentAccountId: 'currentAccountId',
  subAccountId: 'subAccountId',
  type: 'type',
  description: 'description',
  paymentMethod: 'paymentMethod'
};

exports.Prisma.InvoiceOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  currentAccountId: 'currentAccountId',
  status: 'status',
  type: 'type',
  externalLink: 'externalLink',
  notes: 'notes',
  companyId: 'companyId'
};

exports.Prisma.BankOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  accountNumber: 'accountNumber',
  iban: 'iban',
  currency: 'currency',
  logo: 'logo',
  branch: 'branch',
  type: 'type'
};

exports.Prisma.OrderOrderByRelevanceFieldEnum = {
  id: 'id',
  currentAccountId: 'currentAccountId',
  status: 'status',
  summary: 'summary',
  type: 'type',
  method: 'method',
  companyId: 'companyId'
};

exports.Prisma.CMSDataOrderByRelevanceFieldEnum = {
  id: 'id',
  heroTitle: 'heroTitle',
  heroSubtitle: 'heroSubtitle',
  buttonText: 'buttonText',
  announcement: 'announcement',
  announcement2: 'announcement2',
  siteName: 'siteName',
  primaryColor: 'primaryColor',
  secondaryColor: 'secondaryColor',
  siteDescription: 'siteDescription',
  categoryTitle: 'categoryTitle',
  categorySubtitle: 'categorySubtitle',
  appTitle: 'appTitle',
  appSubtitle: 'appSubtitle',
  contactPhone: 'contactPhone',
  contactEmail: 'contactEmail',
  contactAddress: 'contactAddress',
  socialInstagram: 'socialInstagram',
  socialWhatsapp: 'socialWhatsapp',
  socialFacebook: 'socialFacebook',
  socialYoutube: 'socialYoutube',
  logoFont: 'logoFont',
  logoUrl: 'logoUrl',
  logoWeight: 'logoWeight',
  footerSlogan: 'footerSlogan',
  layoutWidth: 'layoutWidth',
  heroAlignment: 'heroAlignment',
  topBarText1: 'topBarText1',
  topBarText2: 'topBarText2',
  cartDiscountType: 'cartDiscountType',
  companyName: 'companyName',
  bankName: 'bankName',
  bankIban: 'bankIban',
  efaturaPrefix: 'efaturaPrefix',
  earsivPrefix: 'earsivPrefix',
  companyStampUrl: 'companyStampUrl',
  companyOwnerName: 'companyOwnerName',
  companyOwnerSurname: 'companyOwnerSurname',
  companyTaxNo: 'companyTaxNo',
  companyTaxOffice: 'companyTaxOffice',
  companyFax: 'companyFax',
  companyGsm: 'companyGsm',
  companyKepAddress: 'companyKepAddress',
  companyMersisNo: 'companyMersisNo',
  companySicilNo: 'companySicilNo',
  companyRegion: 'companyRegion',
  companyCountry: 'companyCountry',
  companyCity: 'companyCity',
  companyDistrict: 'companyDistrict',
  companyBuildingName: 'companyBuildingName',
  companyBuildingNo: 'companyBuildingNo',
  companyStreet: 'companyStreet',
  companyPostalCode: 'companyPostalCode',
  companyWebsite: 'companyWebsite',
  companyDefaultUnit: 'companyDefaultUnit',
  companyDefaultLanguages: 'companyDefaultLanguages',
  companyExcludedChars: 'companyExcludedChars',
  companyDefaultTevkifatCode: 'companyDefaultTevkifatCode',
  companyInvoiceFooter: 'companyInvoiceFooter',
  footerText: 'footerText',
  mapCoordinates: 'mapCoordinates',
  dealProductIds: 'dealProductIds',
  paymentMethodsConfig: 'paymentMethodsConfig',
  paytrConfig: 'paytrConfig',
  installmentsConfig: 'installmentsConfig'
};

exports.Prisma.CMSPageOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  status: 'status'
};

exports.Prisma.IntegrationOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type',
  status: 'status',
  lastSync: 'lastSync',
  logo: 'logo'
};

exports.Prisma.IntegrationLogOrderByRelevanceFieldEnum = {
  id: 'id',
  integrationId: 'integrationId',
  time: 'time',
  message: 'message',
  status: 'status'
};

exports.Prisma.StockTransactionOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  productVariantId: 'productVariantId',
  warehouseId: 'warehouseId',
  type: 'type',
  description: 'description',
  userId: 'userId',
  userEmail: 'userEmail',
  moduleSource: 'moduleSource',
  ipAddress: 'ipAddress',
  referenceId: 'referenceId',
  companyId: 'companyId'
};

exports.Prisma.StockTransferOrderByRelevanceFieldEnum = {
  id: 'id',
  transferNo: 'transferNo',
  productId: 'productId',
  fromWarehouseId: 'fromWarehouseId',
  toWarehouseId: 'toWarehouseId',
  status: 'status',
  requester: 'requester',
  approvedBy: 'approvedBy',
  rejectionReason: 'rejectionReason',
  notes: 'notes'
};

exports.Prisma.StockCycleCountOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  warehouseId: 'warehouseId',
  type: 'type',
  status: 'status',
  notes: 'notes',
  createdBy: 'createdBy'
};

exports.Prisma.StockCycleCountItemOrderByRelevanceFieldEnum = {
  id: 'id',
  cycleCountId: 'cycleCountId',
  productId: 'productId',
  rack: 'rack',
  notes: 'notes'
};

exports.Prisma.CouponOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  discountType: 'discountType'
};

exports.Prisma.TicketOrderByRelevanceFieldEnum = {
  id: 'id',
  email: 'email',
  subject: 'subject',
  status: 'status',
  category: 'category',
  orderId: 'orderId'
};

exports.Prisma.TicketMessageOrderByRelevanceFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  sender: 'sender',
  message: 'message'
};

exports.Prisma.CampaignOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  type: 'type',
  startDate: 'startDate',
  endDate: 'endDate',
  target: 'target',
  description: 'description'
};

exports.Prisma.FeedbackOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  message: 'message',
  status: 'status',
  reply: 'reply'
};

exports.Prisma.BlogPostOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  slug: 'slug',
  content: 'content',
  category: 'category',
  image: 'image',
  metaDesc: 'metaDesc'
};

exports.Prisma.AccountingAccountOrderByRelevanceFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  type: 'type',
  parentCode: 'parentCode'
};

exports.Prisma.JournalEntryOrderByRelevanceFieldEnum = {
  id: 'id',
  number: 'number',
  description: 'description',
  status: 'status',
  type: 'type',
  createdBy: 'createdBy',
  referenceId: 'referenceId',
  companyId: 'companyId'
};

exports.Prisma.JournalLineOrderByRelevanceFieldEnum = {
  id: 'id',
  journalEntryId: 'journalEntryId',
  debitAccountId: 'debitAccountId',
  creditAccountId: 'creditAccountId',
  description: 'description'
};

exports.Prisma.ExpenseOrderByRelevanceFieldEnum = {
  id: 'id',
  category: 'category',
  description: 'description',
  supplier: 'supplier',
  receiptNo: 'receiptNo',
  paymentMethod: 'paymentMethod',
  bankId: 'bankId',
  status: 'status',
  companyId: 'companyId'
};

exports.Prisma.BudgetItemOrderByRelevanceFieldEnum = {
  id: 'id',
  category: 'category',
  notes: 'notes'
};

exports.Prisma.TaxDeclarationOrderByRelevanceFieldEnum = {
  id: 'id',
  period: 'period',
  type: 'type',
  status: 'status',
  notes: 'notes'
};

exports.Prisma.InvoiceItemOrderByRelevanceFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  name: 'name'
};

exports.Prisma.IncomeOrderByRelevanceFieldEnum = {
  id: 'id',
  category: 'category',
  description: 'description',
  currentAccountId: 'currentAccountId',
  paymentMethod: 'paymentMethod',
  bankId: 'bankId',
  status: 'status',
  companyId: 'companyId'
};

exports.Prisma.AuthLogOrderByRelevanceFieldEnum = {
  id: 'id',
  ip: 'ip',
  userId: 'userId',
  route: 'route',
  method: 'method',
  failReason: 'failReason'
};

exports.Prisma.MediaItemOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  url: 'url',
  size: 'size',
  tag: 'tag',
  alt: 'alt'
};

exports.Prisma.ProductUnitOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name'
};

exports.Prisma.ProductionPlanOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  status: 'status'
};

exports.Prisma.WorkstationOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  code: 'code',
  unit: 'unit'
};

exports.Prisma.RouteStepOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  workstationId: 'workstationId'
};

exports.Prisma.WasteLogOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  productVariantId: 'productVariantId',
  productionOrderId: 'productionOrderId',
  warehouseId: 'warehouseId',
  reason: 'reason'
};

exports.Prisma.PurchaseRequisitionOrderByRelevanceFieldEnum = {
  id: 'id',
  requisitionNo: 'requisitionNo',
  branchId: 'branchId',
  departmentId: 'departmentId',
  requesterId: 'requesterId',
  projectId: 'projectId',
  costCenterId: 'costCenterId',
  priority: 'priority',
  status: 'status',
  approvalStatus: 'approvalStatus',
  notes: 'notes'
};

exports.Prisma.PurchaseRequisitionItemOrderByRelevanceFieldEnum = {
  id: 'id',
  requisitionId: 'requisitionId',
  productId: 'productId',
  warehouseId: 'warehouseId',
  description: 'description'
};

exports.Prisma.PurchaseRequisitionApprovalOrderByRelevanceFieldEnum = {
  id: 'id',
  requisitionId: 'requisitionId',
  approverId: 'approverId',
  action: 'action',
  comment: 'comment'
};

exports.Prisma.DespatchAdviceOrderByRelevanceFieldEnum = {
  id: 'id',
  despatchNo: 'despatchNo',
  ettnNo: 'ettnNo',
  customerAccountId: 'customerAccountId',
  invoiceId: 'invoiceId',
  orderId: 'orderId',
  carrierId: 'carrierId',
  driverName: 'driverName',
  driverIdentityNo: 'driverIdentityNo',
  licensePlate: 'licensePlate',
  status: 'status'
};

exports.Prisma.DespatchLineOrderByRelevanceFieldEnum = {
  id: 'id',
  despatchId: 'despatchId',
  productId: 'productId'
};

exports.Prisma.RoleOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.PermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name'
};

exports.Prisma.RolePermissionOrderByRelevanceFieldEnum = {
  roleId: 'roleId',
  permissionId: 'permissionId'
};

exports.Prisma.UserRoleOrderByRelevanceFieldEnum = {
  userId: 'userId',
  roleId: 'roleId'
};

exports.Prisma.SystemAuditLogOrderByRelevanceFieldEnum = {
  id: 'id',
  tableName: 'tableName',
  recordId: 'recordId',
  action: 'action',
  userId: 'userId',
  companyId: 'companyId'
};

exports.Prisma.B2BGroupOrderByRelevanceFieldEnum = {
  id: 'id',
  group_name: 'group_name'
};

exports.Prisma.ProductB2BPriceOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  b2bGroupId: 'b2bGroupId'
};

exports.Prisma.TieredPricingOrderByRelevanceFieldEnum = {
  id: 'id',
  productId: 'productId',
  b2bGroupId: 'b2bGroupId'
};

exports.Prisma.AdminNotificationOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  message: 'message',
  type: 'type',
  orderId: 'orderId'
};

exports.Prisma.FeatureModuleOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  description: 'description'
};

exports.Prisma.CompanyPermissionOrderByRelevanceFieldEnum = {
  id: 'id',
  companyId: 'companyId',
  featureModuleId: 'featureModuleId'
};

exports.Prisma.FailedCargoRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  carrierName: 'carrierName',
  requestPayload: 'requestPayload',
  errorMessage: 'errorMessage',
  status: 'status'
};

exports.Prisma.EmailTemplateOrderByRelevanceFieldEnum = {
  id: 'id',
  eventType: 'eventType',
  name: 'name',
  subject: 'subject',
  bodyHtml: 'bodyHtml',
  variables: 'variables',
  status: 'status'
};

exports.Prisma.EmailLogOrderByRelevanceFieldEnum = {
  id: 'id',
  recipient: 'recipient',
  subject: 'subject',
  bodyHtml: 'bodyHtml',
  eventType: 'eventType',
  status: 'status',
  errorMessage: 'errorMessage'
};


exports.Prisma.ModelName = {
  Company: 'Company',
  Account: 'Account',
  Session: 'Session',
  User: 'User',
  VerificationToken: 'VerificationToken',
  Address: 'Address',
  Product: 'Product',
  CategoryDetail: 'CategoryDetail',
  ProductVariant: 'ProductVariant',
  StockLocation: 'StockLocation',
  Warehouse: 'Warehouse',
  Branch: 'Branch',
  RecipeItem: 'RecipeItem',
  ProductionOrder: 'ProductionOrder',
  CurrentAccount: 'CurrentAccount',
  SubAccount: 'SubAccount',
  Transaction: 'Transaction',
  Invoice: 'Invoice',
  Bank: 'Bank',
  Order: 'Order',
  CMSData: 'CMSData',
  CMSPage: 'CMSPage',
  Integration: 'Integration',
  IntegrationLog: 'IntegrationLog',
  StockTransaction: 'StockTransaction',
  StockTransfer: 'StockTransfer',
  StockCycleCount: 'StockCycleCount',
  StockCycleCountItem: 'StockCycleCountItem',
  Coupon: 'Coupon',
  Ticket: 'Ticket',
  TicketMessage: 'TicketMessage',
  Campaign: 'Campaign',
  Feedback: 'Feedback',
  BlogPost: 'BlogPost',
  AccountingAccount: 'AccountingAccount',
  JournalEntry: 'JournalEntry',
  JournalLine: 'JournalLine',
  Expense: 'Expense',
  BudgetItem: 'BudgetItem',
  TaxDeclaration: 'TaxDeclaration',
  InvoiceItem: 'InvoiceItem',
  Income: 'Income',
  AuthLog: 'AuthLog',
  MediaItem: 'MediaItem',
  ProductUnit: 'ProductUnit',
  ProductionPlan: 'ProductionPlan',
  Workstation: 'Workstation',
  RouteStep: 'RouteStep',
  WasteLog: 'WasteLog',
  PurchaseRequisition: 'PurchaseRequisition',
  PurchaseRequisitionItem: 'PurchaseRequisitionItem',
  PurchaseRequisitionApproval: 'PurchaseRequisitionApproval',
  DespatchAdvice: 'DespatchAdvice',
  DespatchLine: 'DespatchLine',
  Role: 'Role',
  Permission: 'Permission',
  RolePermission: 'RolePermission',
  UserRole: 'UserRole',
  SystemAuditLog: 'SystemAuditLog',
  B2BGroup: 'B2BGroup',
  ProductB2BPrice: 'ProductB2BPrice',
  TieredPricing: 'TieredPricing',
  AdminNotification: 'AdminNotification',
  FeatureModule: 'FeatureModule',
  CompanyPermission: 'CompanyPermission',
  FailedCargoRequest: 'FailedCargoRequest',
  EmailTemplate: 'EmailTemplate',
  EmailLog: 'EmailLog'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
